// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.ChannelDataLoad
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class TruncateChannelsResponse : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""TruncateChannelsResponse"",""namespace"":""Energistics.Etp.v12.Protocol.ChannelDataLoad"",""fields"":[{""name"":""channelsTruncatedTime"",""type"":{""type"":""map"",""values"":""long""}}],""protocol"":""22"",""messageType"":""10"",""senderRole"":""store"",""protocolRoles"":""store,customer"",""multipartFlag"":true,""fullName"":""Energistics.Etp.v12.Protocol.ChannelDataLoad.TruncateChannelsResponse"",""depends"":[]}");
		private IDictionary<string,System.Int64> _channelsTruncatedTime;
		public virtual Schema Schema
		{
			get
			{
				return TruncateChannelsResponse._SCHEMA;
			}
		}
		public IDictionary<string,System.Int64> ChannelsTruncatedTime
		{
			get
			{
				return this._channelsTruncatedTime;
			}
			set
			{
				this._channelsTruncatedTime = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._channelsTruncatedTime;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._channelsTruncatedTime = (IDictionary<string,System.Int64>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
