// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.DataArray
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class GetDataArrayMetadata : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""GetDataArrayMetadata"",""namespace"":""Energistics.Etp.v12.Protocol.DataArray"",""fields"":[{""name"":""dataArrays"",""type"":{""type"":""map"",""values"":{""type"":""record"",""name"":""DataArrayIdentifier"",""namespace"":""Energistics.Etp.v12.Datatypes.DataArrayTypes"",""fields"":[{""name"":""uri"",""type"":""string""},{""name"":""pathInResource"",""type"":""string""}],""fullName"":""Energistics.Etp.v12.Datatypes.DataArrayTypes.DataArrayIdentifier"",""depends"":[]}}}],""protocol"":""9"",""messageType"":""6"",""senderRole"":""customer"",""protocolRoles"":""store,customer"",""multipartFlag"":false,""fullName"":""Energistics.Etp.v12.Protocol.DataArray.GetDataArrayMetadata"",""depends"":[
  ""Energistics.Etp.v12.Datatypes.DataArrayTypes.DataArrayIdentifier""
]}");
		private IDictionary<string,Energistics.Etp.v12.Datatypes.DataArrayTypes.DataArrayIdentifier> _dataArrays;
		public virtual Schema Schema
		{
			get
			{
				return GetDataArrayMetadata._SCHEMA;
			}
		}
		public IDictionary<string,Energistics.Etp.v12.Datatypes.DataArrayTypes.DataArrayIdentifier> DataArrays
		{
			get
			{
				return this._dataArrays;
			}
			set
			{
				this._dataArrays = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._dataArrays;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._dataArrays = (IDictionary<string,Energistics.Etp.v12.Datatypes.DataArrayTypes.DataArrayIdentifier>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
