// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.DataArray
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class PutUninitializedDataArray : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"PutUninitializedDataArray\",\"namespace\":\"Energistics.Etp." +
				"v12.Protocol.DataArray\",\"fields\":[{\"name\":\"dataArrays\",\"type\":{\"type\":\"map\",\"val" +
				"ues\":{\"type\":\"record\",\"name\":\"PutUninitializedDataArrayType\",\"namespace\":\"Energi" +
				"stics.Etp.v12.Datatypes.DataArrayTypes\",\"fields\":[{\"name\":\"uid\",\"type\":{\"type\":\"" +
				"record\",\"name\":\"DataArrayIdentifier\",\"namespace\":\"Energistics.Etp.v12.Datatypes." +
				"DataArrayTypes\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{\"name\":\"pathInResource" +
				"\",\"type\":\"string\"}],\"fullName\":\"Energistics.Etp.v12.Datatypes.DataArrayTypes.Dat" +
				"aArrayIdentifier\",\"depends\":[]}},{\"name\":\"metadata\",\"type\":{\"type\":\"record\",\"nam" +
				"e\":\"DataArrayMetadata\",\"namespace\":\"Energistics.Etp.v12.Datatypes.DataArrayTypes" +
				"\",\"fields\":[{\"name\":\"dimensions\",\"type\":{\"type\":\"array\",\"items\":\"long\"}},{\"name\"" +
				":\"arrayType\",\"type\":{\"type\":\"enum\",\"name\":\"AnyArrayType\",\"namespace\":\"Energistic" +
				"s.Etp.v12.Datatypes\",\"symbols\":[\"arrayOfBoolean\",\"arrayOfInt\",\"arrayOfLong\",\"arr" +
				"ayOfFloat\",\"arrayOfDouble\",\"arrayOfString\",\"bytes\"],\"fullName\":\"Energistics.Etp." +
				"v12.Datatypes.AnyArrayType\",\"depends\":[]}}],\"fullName\":\"Energistics.Etp.v12.Data" +
				"types.DataArrayTypes.DataArrayMetadata\",\"depends\":[\r\n  \"Energistics.Etp.v12.Data" +
				"types.AnyArrayType\"\r\n]}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.DataArrayTyp" +
				"es.PutUninitializedDataArrayType\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes." +
				"DataArrayTypes.DataArrayIdentifier\",\r\n  \"Energistics.Etp.v12.Datatypes.DataArray" +
				"Types.DataArrayMetadata\"\r\n]}}}],\"protocol\":\"9\",\"messageType\":\"9\",\"senderRole\":\"c" +
				"ustomer\",\"protocolRoles\":\"store,customer\",\"multipartFlag\":false,\"fullName\":\"Ener" +
				"gistics.Etp.v12.Protocol.DataArray.PutUninitializedDataArray\",\"depends\":[\r\n  \"En" +
				"ergistics.Etp.v12.Datatypes.DataArrayTypes.PutUninitializedDataArrayType\"\r\n]}");
		private IDictionary<string,Energistics.Etp.v12.Datatypes.DataArrayTypes.PutUninitializedDataArrayType> _dataArrays;
		public virtual Schema Schema
		{
			get
			{
				return PutUninitializedDataArray._SCHEMA;
			}
		}
		public IDictionary<string,Energistics.Etp.v12.Datatypes.DataArrayTypes.PutUninitializedDataArrayType> DataArrays
		{
			get
			{
				return this._dataArrays;
			}
			set
			{
				this._dataArrays = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._dataArrays;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._dataArrays = (IDictionary<string,Energistics.Etp.v12.Datatypes.DataArrayTypes.PutUninitializedDataArrayType>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
