// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.Discovery
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class GetResources : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""GetResources"",""namespace"":""Energistics.Etp.v12.Protocol.Discovery"",""fields"":[{""name"":""context"",""type"":{""type"":""record"",""name"":""ContextInfo"",""namespace"":""Energistics.Etp.v12.Datatypes.Object"",""fields"":[{""name"":""uri"",""type"":""string""},{""name"":""depth"",""type"":""int""},{""name"":""dataObjectTypes"",""default"":[],""type"":{""type"":""array"",""items"":""string""}}],""fullName"":""Energistics.Etp.v12.Datatypes.Object.ContextInfo"",""depends"":[]}},{""name"":""scope"",""type"":{""type"":""enum"",""name"":""ContextScopeKind"",""namespace"":""Energistics.Etp.v12.Datatypes.Object"",""symbols"":[""self"",""sources"",""targets"",""sourcesOrSelf"",""targetsOrSelf""],""fullName"":""Energistics.Etp.v12.Datatypes.Object.ContextScopeKind"",""depends"":[]}},{""name"":""countObjects"",""default"":false,""type"":""boolean""},{""name"":""lastChangedFilter"",""type"":[""null"",""long""]}],""protocol"":""3"",""messageType"":""1"",""senderRole"":""customer"",""protocolRoles"":""store,customer"",""multipartFlag"":false,""fullName"":""Energistics.Etp.v12.Protocol.Discovery.GetResources"",""depends"":[
  ""Energistics.Etp.v12.Datatypes.Object.ContextInfo"",
  ""Energistics.Etp.v12.Datatypes.Object.ContextScopeKind""
]}");
		private Energistics.Etp.v12.Datatypes.Object.ContextInfo _context;
		private Energistics.Etp.v12.Datatypes.Object.ContextScopeKind _scope;
		private bool _countObjects;
		private System.Nullable<long> _lastChangedFilter;
		public virtual Schema Schema
		{
			get
			{
				return GetResources._SCHEMA;
			}
		}
		public Energistics.Etp.v12.Datatypes.Object.ContextInfo Context
		{
			get
			{
				return this._context;
			}
			set
			{
				this._context = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.Object.ContextScopeKind Scope
		{
			get
			{
				return this._scope;
			}
			set
			{
				this._scope = value;
			}
		}
		public bool CountObjects
		{
			get
			{
				return this._countObjects;
			}
			set
			{
				this._countObjects = value;
			}
		}
		public System.Nullable<long> LastChangedFilter
		{
			get
			{
				return this._lastChangedFilter;
			}
			set
			{
				this._lastChangedFilter = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._context;
			case 1: return this._scope;
			case 2: return this._countObjects;
			case 3: return this._lastChangedFilter;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._context = (Energistics.Etp.v12.Datatypes.Object.ContextInfo)fieldValue; break;
			case 1: this._scope = (Energistics.Etp.v12.Datatypes.Object.ContextScopeKind)fieldValue; break;
			case 2: this._countObjects = (System.Boolean)fieldValue; break;
			case 3: this._lastChangedFilter = (System.Nullable<long>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
