// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class ServerCapabilities : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ServerCapabilities\",\"namespace\":\"Energistics.Etp.v12.Dat" +
				"atypes\",\"fields\":[{\"name\":\"applicationName\",\"type\":\"string\"},{\"name\":\"applicatio" +
				"nVersion\",\"type\":\"string\"},{\"name\":\"contactInformation\",\"type\":{\"type\":\"record\"," +
				"\"name\":\"Contact\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"" +
				"organizationName\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"contactName\",\"default\":" +
				"\"\",\"type\":\"string\"},{\"name\":\"contactPhone\",\"default\":\"\",\"type\":\"string\"},{\"name\"" +
				":\"contactEmail\",\"default\":\"\",\"type\":\"string\"}],\"fullName\":\"Energistics.Etp.v12.D" +
				"atatypes.Contact\",\"depends\":[]}},{\"name\":\"supportedCompression\",\"default\":[],\"ty" +
				"pe\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"supportedEncodings\",\"type\":\"stri" +
				"ng\"},{\"name\":\"supportedFormats\",\"default\":[\"xml\"],\"type\":{\"type\":\"array\",\"items\"" +
				":\"string\"}},{\"name\":\"supportedObjects\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}" +
				",{\"name\":\"supportedProtocols\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"n" +
				"ame\":\"SupportedProtocol\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{" +
				"\"name\":\"protocol\",\"type\":\"int\"},{\"name\":\"protocolVersion\",\"type\":{\"type\":\"record" +
				"\",\"name\":\"Version\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\"" +
				":\"major\",\"default\":0,\"type\":\"int\"},{\"name\":\"minor\",\"default\":0,\"type\":\"int\"},{\"n" +
				"ame\":\"revision\",\"default\":0,\"type\":\"int\"},{\"name\":\"patch\",\"default\":0,\"type\":\"in" +
				"t\"}],\"fullName\":\"Energistics.Etp.v12.Datatypes.Version\",\"depends\":[]}},{\"name\":\"" +
				"role\",\"type\":\"string\"},{\"name\":\"protocolCapabilities\",\"default\":{},\"type\":{\"type" +
				"\":\"map\",\"values\":{\"type\":\"record\",\"name\":\"DataValue\",\"namespace\":\"Energistics.Et" +
				"p.v12.Datatypes\",\"fields\":[{\"name\":\"item\",\"type\":[\"null\",\"boolean\",\"int\",\"long\"," +
				"\"float\",\"double\",\"string\",{\"type\":\"record\",\"name\":\"ArrayOfBoolean\",\"namespace\":\"" +
				"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\"" +
				",\"items\":\"boolean\"}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ArrayOfBoolean\"," +
				"\"depends\":[]},{\"type\":\"record\",\"name\":\"ArrayOfInt\",\"namespace\":\"Energistics.Etp." +
				"v12.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"int\"}}" +
				"],\"fullName\":\"Energistics.Etp.v12.Datatypes.ArrayOfInt\",\"depends\":[]},{\"type\":\"r" +
				"ecord\",\"name\":\"ArrayOfLong\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\"" +
				":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"long\"}}],\"fullName\":\"Energist" +
				"ics.Etp.v12.Datatypes.ArrayOfLong\",\"depends\":[]},{\"type\":\"record\",\"name\":\"ArrayO" +
				"fFloat\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"values\",\"" +
				"type\":{\"type\":\"array\",\"items\":\"float\"}}],\"fullName\":\"Energistics.Etp.v12.Datatyp" +
				"es.ArrayOfFloat\",\"depends\":[]},{\"type\":\"record\",\"name\":\"ArrayOfDouble\",\"namespac" +
				"e\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"ar" +
				"ray\",\"items\":\"double\"}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ArrayOfDouble" +
				"\",\"depends\":[]},{\"type\":\"record\",\"name\":\"ArrayOfString\",\"namespace\":\"Energistics" +
				".Etp.v12.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"s" +
				"tring\"}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ArrayOfString\",\"depends\":[]}" +
				",\"bytes\"]}],\"fullName\":\"Energistics.Etp.v12.Datatypes.DataValue\",\"depends\":[\r\n  " +
				"\"Energistics.Etp.v12.Datatypes.ArrayOfBoolean\",\r\n  \"Energistics.Etp.v12.Datatype" +
				"s.ArrayOfInt\",\r\n  \"Energistics.Etp.v12.Datatypes.ArrayOfLong\",\r\n  \"Energistics.E" +
				"tp.v12.Datatypes.ArrayOfFloat\",\r\n  \"Energistics.Etp.v12.Datatypes.ArrayOfDouble\"" +
				",\r\n  \"Energistics.Etp.v12.Datatypes.ArrayOfString\"\r\n]}}}],\"fullName\":\"Energistic" +
				"s.Etp.v12.Datatypes.SupportedProtocol\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datat" +
				"ypes.Version\",\r\n  \"Energistics.Etp.v12.Datatypes.DataValue\"\r\n]}}},{\"name\":\"endpo" +
				"intCapabilities\",\"default\":{},\"type\":{\"type\":\"map\",\"values\":\"DataValue\"}}],\"full" +
				"Name\":\"Energistics.Etp.v12.Datatypes.ServerCapabilities\",\"depends\":[\r\n  \"Energis" +
				"tics.Etp.v12.Datatypes.Contact\",\r\n  \"Energistics.Etp.v12.Datatypes.SupportedProt" +
				"ocol\",\r\n  \"Energistics.Etp.v12.Datatypes.DataValue\"\r\n]}");
		private string _applicationName;
		private string _applicationVersion;
		private Energistics.Etp.v12.Datatypes.Contact _contactInformation;
		private IList<System.String> _supportedCompression;
		private string _supportedEncodings;
		private IList<System.String> _supportedFormats;
		private IList<System.String> _supportedObjects;
		private IList<Energistics.Etp.v12.Datatypes.SupportedProtocol> _supportedProtocols;
		private IDictionary<string,Energistics.Etp.v12.Datatypes.DataValue> _endpointCapabilities;
		public virtual Schema Schema
		{
			get
			{
				return ServerCapabilities._SCHEMA;
			}
		}
		public string ApplicationName
		{
			get
			{
				return this._applicationName;
			}
			set
			{
				this._applicationName = value;
			}
		}
		public string ApplicationVersion
		{
			get
			{
				return this._applicationVersion;
			}
			set
			{
				this._applicationVersion = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.Contact ContactInformation
		{
			get
			{
				return this._contactInformation;
			}
			set
			{
				this._contactInformation = value;
			}
		}
		public IList<System.String> SupportedCompression
		{
			get
			{
				return this._supportedCompression;
			}
			set
			{
				this._supportedCompression = value;
			}
		}
		public string SupportedEncodings
		{
			get
			{
				return this._supportedEncodings;
			}
			set
			{
				this._supportedEncodings = value;
			}
		}
		public IList<System.String> SupportedFormats
		{
			get
			{
				return this._supportedFormats;
			}
			set
			{
				this._supportedFormats = value;
			}
		}
		public IList<System.String> SupportedObjects
		{
			get
			{
				return this._supportedObjects;
			}
			set
			{
				this._supportedObjects = value;
			}
		}
		public IList<Energistics.Etp.v12.Datatypes.SupportedProtocol> SupportedProtocols
		{
			get
			{
				return this._supportedProtocols;
			}
			set
			{
				this._supportedProtocols = value;
			}
		}
		public IDictionary<string,Energistics.Etp.v12.Datatypes.DataValue> EndpointCapabilities
		{
			get
			{
				return this._endpointCapabilities;
			}
			set
			{
				this._endpointCapabilities = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._applicationName;
			case 1: return this._applicationVersion;
			case 2: return this._contactInformation;
			case 3: return this._supportedCompression;
			case 4: return this._supportedEncodings;
			case 5: return this._supportedFormats;
			case 6: return this._supportedObjects;
			case 7: return this._supportedProtocols;
			case 8: return this._endpointCapabilities;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._applicationName = (System.String)fieldValue; break;
			case 1: this._applicationVersion = (System.String)fieldValue; break;
			case 2: this._contactInformation = (Energistics.Etp.v12.Datatypes.Contact)fieldValue; break;
			case 3: this._supportedCompression = (IList<System.String>)fieldValue; break;
			case 4: this._supportedEncodings = (System.String)fieldValue; break;
			case 5: this._supportedFormats = (IList<System.String>)fieldValue; break;
			case 6: this._supportedObjects = (IList<System.String>)fieldValue; break;
			case 7: this._supportedProtocols = (IList<Energistics.Etp.v12.Datatypes.SupportedProtocol>)fieldValue; break;
			case 8: this._endpointCapabilities = (IDictionary<string,Energistics.Etp.v12.Datatypes.DataValue>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
