// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.GrowingObjectQuery
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class FindPartsResponse : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""FindPartsResponse"",""namespace"":""Energistics.Etp.v12.Protocol.GrowingObjectQuery"",""fields"":[{""name"":""objectParts"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""ObjectPart"",""namespace"":""Energistics.Etp.v12.Datatypes.Object"",""fields"":[{""name"":""uri"",""type"":""string""},{""name"":""uid"",""type"":""string""},{""name"":""contentType"",""type"":""string""},{""name"":""data"",""type"":""bytes""}],""fullName"":""Energistics.Etp.v12.Datatypes.Object.ObjectPart"",""depends"":[]}}},{""name"":""serverSortOrder"",""type"":""string""}],""protocol"":""16"",""messageType"":""2"",""senderRole"":""store"",""protocolRoles"":""store,customer"",""multipartFlag"":true,""fullName"":""Energistics.Etp.v12.Protocol.GrowingObjectQuery.FindPartsResponse"",""depends"":[
  ""Energistics.Etp.v12.Datatypes.Object.ObjectPart""
]}");
		private IList<Energistics.Etp.v12.Datatypes.Object.ObjectPart> _objectParts;
		private string _serverSortOrder;
		public virtual Schema Schema
		{
			get
			{
				return FindPartsResponse._SCHEMA;
			}
		}
		public IList<Energistics.Etp.v12.Datatypes.Object.ObjectPart> ObjectParts
		{
			get
			{
				return this._objectParts;
			}
			set
			{
				this._objectParts = value;
			}
		}
		public string ServerSortOrder
		{
			get
			{
				return this._serverSortOrder;
			}
			set
			{
				this._serverSortOrder = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._objectParts;
			case 1: return this._serverSortOrder;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._objectParts = (IList<Energistics.Etp.v12.Datatypes.Object.ObjectPart>)fieldValue; break;
			case 1: this._serverSortOrder = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
