// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.StoreNotification
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class ChangeNotification : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ChangeNotification\",\"namespace\":\"Energistics.Etp.v12.Pro" +
				"tocol.StoreNotification\",\"fields\":[{\"name\":\"change\",\"type\":{\"type\":\"record\",\"nam" +
				"e\":\"ObjectChange\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Object\",\"fields\":[{" +
				"\"name\":\"changeKind\",\"type\":{\"type\":\"enum\",\"name\":\"ObjectChangeKind\",\"namespace\":" +
				"\"Energistics.Etp.v12.Datatypes.Object\",\"symbols\":[\"insert\",\"update\",\"authorized\"" +
				"],\"fullName\":\"Energistics.Etp.v12.Datatypes.Object.ObjectChangeKind\",\"depends\":[" +
				"]}},{\"name\":\"changeTime\",\"type\":\"long\"},{\"name\":\"dataObject\",\"type\":{\"type\":\"rec" +
				"ord\",\"name\":\"DataObject\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Object\",\"fie" +
				"lds\":[{\"name\":\"resource\",\"type\":{\"type\":\"record\",\"name\":\"Resource\",\"namespace\":\"" +
				"Energistics.Etp.v12.Datatypes.Object\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{" +
				"\"name\":\"contentType\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"c" +
				"hannelSubscribable\",\"default\":false,\"type\":\"boolean\"},{\"name\":\"customData\",\"type" +
				"\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"resourceType\",\"type\":{\"type\":\"enum\"" +
				",\"name\":\"ResourceKind\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Object\",\"symbo" +
				"ls\":[\"DataObject\",\"Folder\",\"UriProtocol\"],\"fullName\":\"Energistics.Etp.v12.Dataty" +
				"pes.Object.ResourceKind\",\"depends\":[]}},{\"name\":\"childCount\",\"default\":null,\"typ" +
				"e\":[\"null\",\"int\"]},{\"name\":\"uuid\",\"type\":[\"null\",{\"type\":\"fixed\",\"name\":\"Uuid\",\"" +
				"namespace\":\"Energistics.Etp.v12.Datatypes\",\"size\":16,\"fullName\":\"Energistics.Etp" +
				".v12.Datatypes.Uuid\",\"depends\":[]}]},{\"name\":\"lastChanged\",\"type\":[\"null\",\"long\"" +
				"]},{\"name\":\"objectNotifiable\",\"default\":false,\"type\":\"boolean\"}],\"fullName\":\"Ene" +
				"rgistics.Etp.v12.Datatypes.Object.Resource\",\"depends\":[\r\n  \"Energistics.Etp.v12." +
				"Datatypes.Object.ResourceKind\",\r\n  \"Energistics.Etp.v12.Datatypes.Uuid\"\r\n]}},{\"n" +
				"ame\":\"data\",\"type\":\"bytes\"}],\"fullName\":\"Energistics.Etp.v12.Datatypes.Object.Da" +
				"taObject\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.Object.Resource\"\r\n]}}],\"" +
				"fullName\":\"Energistics.Etp.v12.Datatypes.Object.ObjectChange\",\"depends\":[\r\n  \"En" +
				"ergistics.Etp.v12.Datatypes.Object.ObjectChangeKind\",\r\n  \"Energistics.Etp.v12.Da" +
				"tatypes.Object.DataObject\"\r\n]}}],\"protocol\":\"5\",\"messageType\":\"2\",\"senderRole\":\"" +
				"store\",\"protocolRoles\":\"store,customer\",\"multipartFlag\":false,\"fullName\":\"Energi" +
				"stics.Etp.v12.Protocol.StoreNotification.ChangeNotification\",\"depends\":[\r\n  \"Ene" +
				"rgistics.Etp.v12.Datatypes.Object.ObjectChange\"\r\n]}");
		private Energistics.Etp.v12.Datatypes.Object.ObjectChange _change;
		public virtual Schema Schema
		{
			get
			{
				return ChangeNotification._SCHEMA;
			}
		}
		public Energistics.Etp.v12.Datatypes.Object.ObjectChange Change
		{
			get
			{
				return this._change;
			}
			set
			{
				this._change = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._change;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._change = (Energistics.Etp.v12.Datatypes.Object.ObjectChange)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
