// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.StoreNotification
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class ObjectChanged : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ObjectChanged\",\"namespace\":\"Energistics.Etp.v12.Protocol" +
				".StoreNotification\",\"fields\":[{\"name\":\"change\",\"type\":{\"type\":\"record\",\"name\":\"O" +
				"bjectChange\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Object\",\"fields\":[{\"name" +
				"\":\"changeKind\",\"type\":{\"type\":\"enum\",\"name\":\"ObjectChangeKind\",\"namespace\":\"Ener" +
				"gistics.Etp.v12.Datatypes.Object\",\"symbols\":[\"insert\",\"update\",\"authorized\"],\"fu" +
				"llName\":\"Energistics.Etp.v12.Datatypes.Object.ObjectChangeKind\",\"depends\":[]}},{" +
				"\"name\":\"changeTime\",\"type\":\"long\"},{\"name\":\"dataObject\",\"type\":{\"type\":\"record\"," +
				"\"name\":\"DataObject\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Object\",\"fields\":" +
				"[{\"name\":\"resource\",\"type\":{\"type\":\"record\",\"name\":\"Resource\",\"namespace\":\"Energ" +
				"istics.Etp.v12.Datatypes.Object\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{\"name" +
				"\":\"contentType\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"object" +
				"Notifiable\",\"default\":true,\"type\":\"boolean\"},{\"name\":\"resourceType\",\"type\":{\"typ" +
				"e\":\"enum\",\"name\":\"ResourceKind\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Objec" +
				"t\",\"symbols\":[\"DataObject\",\"Folder\",\"UriProtocol\",\"DataSpace\"],\"fullName\":\"Energ" +
				"istics.Etp.v12.Datatypes.Object.ResourceKind\",\"depends\":[]}},{\"name\":\"sourceCoun" +
				"t\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"targetCount\",\"default\":null,\"t" +
				"ype\":[\"null\",\"int\"]},{\"name\":\"contentCount\",\"default\":null,\"type\":[\"null\",\"int\"]" +
				"},{\"name\":\"lastChanged\",\"type\":[\"null\",\"long\"]},{\"name\":\"customData\",\"type\":{\"ty" +
				"pe\":\"map\",\"values\":\"string\"}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.Object." +
				"Resource\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.Object.ResourceKind\"\r\n]}" +
				"},{\"name\":\"data\",\"type\":\"bytes\"}],\"fullName\":\"Energistics.Etp.v12.Datatypes.Obje" +
				"ct.DataObject\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.Object.Resource\"\r\n]" +
				"}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.Object.ObjectChange\",\"depends\":[\r\n" +
				"  \"Energistics.Etp.v12.Datatypes.Object.ObjectChangeKind\",\r\n  \"Energistics.Etp.v" +
				"12.Datatypes.Object.DataObject\"\r\n]}}],\"protocol\":\"5\",\"messageType\":\"2\",\"senderRo" +
				"le\":\"store\",\"protocolRoles\":\"store,customer\",\"multipartFlag\":false,\"fullName\":\"E" +
				"nergistics.Etp.v12.Protocol.StoreNotification.ObjectChanged\",\"depends\":[\r\n  \"Ene" +
				"rgistics.Etp.v12.Datatypes.Object.ObjectChange\"\r\n]}");
		private Energistics.Etp.v12.Datatypes.Object.ObjectChange _change;
		public virtual Schema Schema
		{
			get
			{
				return ObjectChanged._SCHEMA;
			}
		}
		public Energistics.Etp.v12.Datatypes.Object.ObjectChange Change
		{
			get
			{
				return this._change;
			}
			set
			{
				this._change = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._change;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._change = (Energistics.Etp.v12.Datatypes.Object.ObjectChange)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
