// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.StoreNotification
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class ObjectChanged : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ObjectChanged\",\"namespace\":\"Energistics.Etp.v12.Protocol" +
				".StoreNotification\",\"fields\":[{\"name\":\"change\",\"type\":{\"type\":\"record\",\"name\":\"O" +
				"bjectChange\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Object\",\"fields\":[{\"name" +
				"\":\"changeKind\",\"type\":{\"type\":\"enum\",\"name\":\"ObjectChangeKind\",\"namespace\":\"Ener" +
				"gistics.Etp.v12.Datatypes.Object\",\"symbols\":[\"insert\",\"update\",\"authorized\"],\"fu" +
				"llName\":\"Energistics.Etp.v12.Datatypes.Object.ObjectChangeKind\",\"depends\":[]}},{" +
				"\"name\":\"changeTime\",\"type\":\"long\"},{\"name\":\"dataObject\",\"type\":{\"type\":\"record\"," +
				"\"name\":\"DataObject\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Object\",\"fields\":" +
				"[{\"name\":\"resource\",\"type\":{\"type\":\"record\",\"name\":\"Resource\",\"namespace\":\"Energ" +
				"istics.Etp.v12.Datatypes.Object\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{\"name" +
				"\":\"alternateUris\",\"default\":[],\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\"" +
				":\"dataObjectType\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"sour" +
				"ceCount\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"targetCount\",\"default\":n" +
				"ull,\"type\":[\"null\",\"int\"]},{\"name\":\"lastChanged\",\"type\":\"long\"},{\"name\":\"customD" +
				"ata\",\"default\":{},\"type\":{\"type\":\"map\",\"values\":\"string\"}}],\"fullName\":\"Energist" +
				"ics.Etp.v12.Datatypes.Object.Resource\",\"depends\":[]}},{\"name\":\"format\",\"default\"" +
				":\"xml\",\"type\":\"string\"},{\"name\":\"blobId\",\"type\":[\"null\",{\"type\":\"fixed\",\"name\":\"" +
				"Uuid\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"size\":16,\"fullName\":\"Energist" +
				"ics.Etp.v12.Datatypes.Uuid\",\"depends\":[]}]},{\"name\":\"data\",\"default\":\"\",\"type\":\"" +
				"bytes\"}],\"fullName\":\"Energistics.Etp.v12.Datatypes.Object.DataObject\",\"depends\":" +
				"[\r\n  \"Energistics.Etp.v12.Datatypes.Object.Resource\",\r\n  \"Energistics.Etp.v12.Da" +
				"tatypes.Uuid\"\r\n]}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.Object.ObjectChang" +
				"e\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.Object.ObjectChangeKind\",\r\n  \"E" +
				"nergistics.Etp.v12.Datatypes.Object.DataObject\"\r\n]}},{\"name\":\"requestUuid\",\"type" +
				"\":\"Energistics.Etp.v12.Datatypes.Uuid\"}],\"protocol\":\"5\",\"messageType\":\"2\",\"sende" +
				"rRole\":\"store\",\"protocolRoles\":\"store,customer\",\"multipartFlag\":false,\"fullName\"" +
				":\"Energistics.Etp.v12.Protocol.StoreNotification.ObjectChanged\",\"depends\":[\r\n  \"" +
				"Energistics.Etp.v12.Datatypes.Object.ObjectChange\",\r\n  \"Energistics.Etp.v12.Data" +
				"types.Uuid\"\r\n]}");
		private Energistics.Etp.v12.Datatypes.Object.ObjectChange _change;
		private Energistics.Etp.v12.Datatypes.Uuid _requestUuid;
		public virtual Schema Schema
		{
			get
			{
				return ObjectChanged._SCHEMA;
			}
		}
		public Energistics.Etp.v12.Datatypes.Object.ObjectChange Change
		{
			get
			{
				return this._change;
			}
			set
			{
				this._change = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.Uuid RequestUuid
		{
			get
			{
				return this._requestUuid;
			}
			set
			{
				this._requestUuid = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._change;
			case 1: return this._requestUuid;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._change = (Energistics.Etp.v12.Datatypes.Object.ObjectChange)fieldValue; break;
			case 1: this._requestUuid = (Energistics.Etp.v12.Datatypes.Uuid)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
