// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.StoreNotification
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class SubscribeNotifications : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"SubscribeNotifications\",\"namespace\":\"Energistics.Etp.v12" +
				".Protocol.StoreNotification\",\"fields\":[{\"name\":\"request\",\"type\":{\"type\":\"record\"" +
				",\"name\":\"SubscriptionInfo\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Object\",\"f" +
				"ields\":[{\"name\":\"context\",\"type\":{\"type\":\"record\",\"name\":\"ContextInfo\",\"namespac" +
				"e\":\"Energistics.Etp.v12.Datatypes.Object\",\"fields\":[{\"name\":\"uri\",\"type\":\"string" +
				"\"},{\"name\":\"depth\",\"type\":\"int\"},{\"name\":\"dataObjectTypes\",\"default\":[],\"type\":{" +
				"\"type\":\"array\",\"items\":\"string\"}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.Obj" +
				"ect.ContextInfo\",\"depends\":[]}},{\"name\":\"scope\",\"type\":{\"type\":\"enum\",\"name\":\"Co" +
				"ntextScopeKind\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Object\",\"symbols\":[\"s" +
				"elf\",\"sources\",\"targets\",\"sourcesOrSelf\",\"targetsOrSelf\"],\"fullName\":\"Energistic" +
				"s.Etp.v12.Datatypes.Object.ContextScopeKind\",\"depends\":[]}},{\"name\":\"requestUuid" +
				"\",\"type\":{\"type\":\"fixed\",\"name\":\"Uuid\",\"namespace\":\"Energistics.Etp.v12.Datatype" +
				"s\",\"size\":16,\"fullName\":\"Energistics.Etp.v12.Datatypes.Uuid\",\"depends\":[]}},{\"na" +
				"me\":\"startTime\",\"type\":\"long\"},{\"name\":\"includeObjectData\",\"type\":\"boolean\"},{\"n" +
				"ame\":\"format\",\"default\":\"xml\",\"type\":\"string\"}],\"fullName\":\"Energistics.Etp.v12." +
				"Datatypes.Object.SubscriptionInfo\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes" +
				".Object.ContextInfo\",\r\n  \"Energistics.Etp.v12.Datatypes.Object.ContextScopeKind\"" +
				",\r\n  \"Energistics.Etp.v12.Datatypes.Uuid\"\r\n]}}],\"protocol\":\"5\",\"messageType\":\"6\"" +
				",\"senderRole\":\"customer\",\"protocolRoles\":\"store,customer\",\"multipartFlag\":false," +
				"\"fullName\":\"Energistics.Etp.v12.Protocol.StoreNotification.SubscribeNotification" +
				"s\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.Object.SubscriptionInfo\"\r\n]}");
		private Energistics.Etp.v12.Datatypes.Object.SubscriptionInfo _request;
		public virtual Schema Schema
		{
			get
			{
				return SubscribeNotifications._SCHEMA;
			}
		}
		public Energistics.Etp.v12.Datatypes.Object.SubscriptionInfo Request
		{
			get
			{
				return this._request;
			}
			set
			{
				this._request = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._request;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._request = (Energistics.Etp.v12.Datatypes.Object.SubscriptionInfo)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
