// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.StoreNotification
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class UnsolicitedStoreNotifications : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"UnsolicitedStoreNotifications\",\"namespace\":\"Energistics." +
				"Etp.v12.Protocol.StoreNotification\",\"fields\":[{\"name\":\"subscriptions\",\"type\":{\"t" +
				"ype\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"SubscriptionInfo\",\"namespace\":\"Ene" +
				"rgistics.Etp.v12.Datatypes.Object\",\"fields\":[{\"name\":\"context\",\"type\":{\"type\":\"r" +
				"ecord\",\"name\":\"ContextInfo\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Object\",\"" +
				"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{\"name\":\"depth\",\"type\":\"int\"},{\"name\":\"d" +
				"ataObjectTypes\",\"default\":[],\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"" +
				"navigableEdges\",\"type\":{\"type\":\"enum\",\"name\":\"RelationshipKind\",\"namespace\":\"Ene" +
				"rgistics.Etp.v12.Datatypes.Object\",\"symbols\":[\"Primary\",\"Secondary\",\"Both\"],\"ful" +
				"lName\":\"Energistics.Etp.v12.Datatypes.Object.RelationshipKind\",\"depends\":[]}},{\"" +
				"name\":\"includeSecondaryTargets\",\"default\":false,\"type\":\"boolean\"},{\"name\":\"inclu" +
				"deSecondarySources\",\"default\":false,\"type\":\"boolean\"}],\"fullName\":\"Energistics.E" +
				"tp.v12.Datatypes.Object.ContextInfo\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatyp" +
				"es.Object.RelationshipKind\"\r\n]}},{\"name\":\"scope\",\"type\":{\"type\":\"enum\",\"name\":\"C" +
				"ontextScopeKind\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Object\",\"symbols\":[\"" +
				"self\",\"sources\",\"targets\",\"sourcesOrSelf\",\"targetsOrSelf\"],\"fullName\":\"Energisti" +
				"cs.Etp.v12.Datatypes.Object.ContextScopeKind\",\"depends\":[]}},{\"name\":\"requestUui" +
				"d\",\"type\":{\"type\":\"fixed\",\"name\":\"Uuid\",\"namespace\":\"Energistics.Etp.v12.Datatyp" +
				"es\",\"size\":16,\"fullName\":\"Energistics.Etp.v12.Datatypes.Uuid\",\"depends\":[]}},{\"n" +
				"ame\":\"startTime\",\"type\":\"long\"},{\"name\":\"includeObjectData\",\"type\":\"boolean\"},{\"" +
				"name\":\"format\",\"default\":\"xml\",\"type\":\"string\"}],\"fullName\":\"Energistics.Etp.v12" +
				".Datatypes.Object.SubscriptionInfo\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatype" +
				"s.Object.ContextInfo\",\r\n  \"Energistics.Etp.v12.Datatypes.Object.ContextScopeKind" +
				"\",\r\n  \"Energistics.Etp.v12.Datatypes.Uuid\"\r\n]}}}],\"protocol\":\"5\",\"messageType\":\"" +
				"8\",\"senderRole\":\"store\",\"protocolRoles\":\"store,customer\",\"multipartFlag\":false,\"" +
				"fullName\":\"Energistics.Etp.v12.Protocol.StoreNotification.UnsolicitedStoreNotifi" +
				"cations\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.Object.SubscriptionInfo\"\r" +
				"\n]}");
		private IList<Energistics.Etp.v12.Datatypes.Object.SubscriptionInfo> _subscriptions;
		public virtual Schema Schema
		{
			get
			{
				return UnsolicitedStoreNotifications._SCHEMA;
			}
		}
		public IList<Energistics.Etp.v12.Datatypes.Object.SubscriptionInfo> Subscriptions
		{
			get
			{
				return this._subscriptions;
			}
			set
			{
				this._subscriptions = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._subscriptions;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._subscriptions = (IList<Energistics.Etp.v12.Datatypes.Object.SubscriptionInfo>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
