// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v11.Protocol.ChannelStreaming
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class ChannelRemove : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""ChannelRemove"",""namespace"":""Energistics.Protocol.ChannelStreaming"",""fields"":[{""name"":""channelId"",""type"":""long""},{""name"":""removeReason"",""type"":[""null"",""string""]}],""messageType"":""8"",""protocol"":""1"",""senderRole"":""producer"",""protocolRoles"":""producer,consumer"",""fullName"":""Energistics.Protocol.ChannelStreaming.ChannelRemove"",""depends"":[]}");
		private long _channelId;
		private string _removeReason;
		public virtual Schema Schema
		{
			get
			{
				return ChannelRemove._SCHEMA;
			}
		}
		public long ChannelId
		{
			get
			{
				return this._channelId;
			}
			set
			{
				this._channelId = value;
			}
		}
		public string RemoveReason
		{
			get
			{
				return this._removeReason;
			}
			set
			{
				this._removeReason = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._channelId;
			case 1: return this._removeReason;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._channelId = (System.Int64)fieldValue; break;
			case 1: this._removeReason = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
