// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.GrowingObjectNotification
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class PartsReplacedByRange : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"PartsReplacedByRange\",\"namespace\":\"Energistics.Etp.v12.P" +
				"rotocol.GrowingObjectNotification\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{\"na" +
				"me\":\"requestUuid\",\"type\":{\"type\":\"fixed\",\"name\":\"Uuid\",\"namespace\":\"Energistics." +
				"Etp.v12.Datatypes\",\"size\":16,\"fullName\":\"Energistics.Etp.v12.Datatypes.Uuid\",\"de" +
				"pends\":[]}},{\"name\":\"changeTime\",\"type\":\"long\"},{\"name\":\"deletedInterval\",\"type\"" +
				":{\"type\":\"record\",\"name\":\"IndexInterval\",\"namespace\":\"Energistics.Etp.v12.Dataty" +
				"pes.Object\",\"fields\":[{\"name\":\"startIndex\",\"type\":{\"type\":\"record\",\"name\":\"Index" +
				"Value\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"item\",\"typ" +
				"e\":[\"null\",\"long\",\"double\"]}],\"fullName\":\"Energistics.Etp.v12.Datatypes.IndexVal" +
				"ue\",\"depends\":[]}},{\"name\":\"endIndex\",\"type\":\"Energistics.Etp.v12.Datatypes.Inde" +
				"xValue\"},{\"name\":\"uom\",\"type\":\"string\"},{\"name\":\"depthDatum\",\"default\":\"\",\"type\"" +
				":\"string\"}],\"fullName\":\"Energistics.Etp.v12.Datatypes.Object.IndexInterval\",\"dep" +
				"ends\":[\r\n  \"Energistics.Etp.v12.Datatypes.IndexValue\",\r\n  \"Energistics.Etp.v12.D" +
				"atatypes.IndexValue\"\r\n]}},{\"name\":\"includeOverlappingIntervals\",\"type\":\"boolean\"" +
				"},{\"name\":\"format\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"parts\",\"type\":{\"type\":" +
				"\"array\",\"items\":{\"type\":\"record\",\"name\":\"ObjectPart\",\"namespace\":\"Energistics.Et" +
				"p.v12.Datatypes.Object\",\"fields\":[{\"name\":\"uid\",\"type\":\"string\"},{\"name\":\"data\"," +
				"\"type\":\"bytes\"}],\"fullName\":\"Energistics.Etp.v12.Datatypes.Object.ObjectPart\",\"d" +
				"epends\":[]}}}],\"protocol\":\"7\",\"messageType\":\"6\",\"senderRole\":\"store\",\"protocolRo" +
				"les\":\"store,customer\",\"multipartFlag\":true,\"fullName\":\"Energistics.Etp.v12.Proto" +
				"col.GrowingObjectNotification.PartsReplacedByRange\",\"depends\":[\r\n  \"Energistics." +
				"Etp.v12.Datatypes.Uuid\",\r\n  \"Energistics.Etp.v12.Datatypes.Object.IndexInterval\"" +
				",\r\n  \"Energistics.Etp.v12.Datatypes.Object.ObjectPart\"\r\n]}");
		private string _uri;
		private Energistics.Etp.v12.Datatypes.Uuid _requestUuid;
		private long _changeTime;
		private Energistics.Etp.v12.Datatypes.Object.IndexInterval _deletedInterval;
		private bool _includeOverlappingIntervals;
		private string _format;
		private IList<Energistics.Etp.v12.Datatypes.Object.ObjectPart> _parts;
		public virtual Schema Schema
		{
			get
			{
				return PartsReplacedByRange._SCHEMA;
			}
		}
		public string Uri
		{
			get
			{
				return this._uri;
			}
			set
			{
				this._uri = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.Uuid RequestUuid
		{
			get
			{
				return this._requestUuid;
			}
			set
			{
				this._requestUuid = value;
			}
		}
		public long ChangeTime
		{
			get
			{
				return this._changeTime;
			}
			set
			{
				this._changeTime = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.Object.IndexInterval DeletedInterval
		{
			get
			{
				return this._deletedInterval;
			}
			set
			{
				this._deletedInterval = value;
			}
		}
		public bool IncludeOverlappingIntervals
		{
			get
			{
				return this._includeOverlappingIntervals;
			}
			set
			{
				this._includeOverlappingIntervals = value;
			}
		}
		public string Format
		{
			get
			{
				return this._format;
			}
			set
			{
				this._format = value;
			}
		}
		public IList<Energistics.Etp.v12.Datatypes.Object.ObjectPart> Parts
		{
			get
			{
				return this._parts;
			}
			set
			{
				this._parts = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._uri;
			case 1: return this._requestUuid;
			case 2: return this._changeTime;
			case 3: return this._deletedInterval;
			case 4: return this._includeOverlappingIntervals;
			case 5: return this._format;
			case 6: return this._parts;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._uri = (System.String)fieldValue; break;
			case 1: this._requestUuid = (Energistics.Etp.v12.Datatypes.Uuid)fieldValue; break;
			case 2: this._changeTime = (System.Int64)fieldValue; break;
			case 3: this._deletedInterval = (Energistics.Etp.v12.Datatypes.Object.IndexInterval)fieldValue; break;
			case 4: this._includeOverlappingIntervals = (System.Boolean)fieldValue; break;
			case 5: this._format = (System.String)fieldValue; break;
			case 6: this._parts = (IList<Energistics.Etp.v12.Datatypes.Object.ObjectPart>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
