// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.GrowingObjectNotification
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class SubscribePartNotifications : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"SubscribePartNotifications\",\"namespace\":\"Energistics.Etp" +
				".v12.Protocol.GrowingObjectNotification\",\"fields\":[{\"name\":\"request\",\"type\":{\"ty" +
				"pe\":\"map\",\"values\":{\"type\":\"record\",\"name\":\"SubscriptionInfo\",\"namespace\":\"Energ" +
				"istics.Etp.v12.Datatypes.Object\",\"fields\":[{\"name\":\"context\",\"type\":{\"type\":\"rec" +
				"ord\",\"name\":\"ContextInfo\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Object\",\"fi" +
				"elds\":[{\"name\":\"uri\",\"type\":\"string\"},{\"name\":\"depth\",\"type\":\"int\"},{\"name\":\"dat" +
				"aObjectTypes\",\"default\":[],\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"na" +
				"vigableEdges\",\"type\":{\"type\":\"enum\",\"name\":\"RelationshipKind\",\"namespace\":\"Energ" +
				"istics.Etp.v12.Datatypes.Object\",\"symbols\":[\"Primary\",\"Secondary\",\"Both\"],\"fullN" +
				"ame\":\"Energistics.Etp.v12.Datatypes.Object.RelationshipKind\",\"depends\":[]}},{\"na" +
				"me\":\"includeSecondaryTargets\",\"default\":false,\"type\":\"boolean\"},{\"name\":\"include" +
				"SecondarySources\",\"default\":false,\"type\":\"boolean\"}],\"fullName\":\"Energistics.Etp" +
				".v12.Datatypes.Object.ContextInfo\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes" +
				".Object.RelationshipKind\"\r\n]}},{\"name\":\"scope\",\"type\":{\"type\":\"enum\",\"name\":\"Con" +
				"textScopeKind\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Object\",\"symbols\":[\"se" +
				"lf\",\"sources\",\"targets\",\"sourcesOrSelf\",\"targetsOrSelf\"],\"fullName\":\"Energistics" +
				".Etp.v12.Datatypes.Object.ContextScopeKind\",\"depends\":[]}},{\"name\":\"requestUuid\"" +
				",\"type\":{\"type\":\"fixed\",\"name\":\"Uuid\",\"namespace\":\"Energistics.Etp.v12.Datatypes" +
				"\",\"size\":16,\"fullName\":\"Energistics.Etp.v12.Datatypes.Uuid\",\"depends\":[]}},{\"nam" +
				"e\":\"startTime\",\"type\":\"long\"},{\"name\":\"includeObjectData\",\"type\":\"boolean\"},{\"na" +
				"me\":\"format\",\"default\":\"xml\",\"type\":\"string\"}],\"fullName\":\"Energistics.Etp.v12.D" +
				"atatypes.Object.SubscriptionInfo\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes." +
				"Object.ContextInfo\",\r\n  \"Energistics.Etp.v12.Datatypes.Object.ContextScopeKind\"," +
				"\r\n  \"Energistics.Etp.v12.Datatypes.Uuid\"\r\n]}}}],\"protocol\":\"7\",\"messageType\":\"7\"" +
				",\"senderRole\":\"customer\",\"protocolRoles\":\"store,customer\",\"multipartFlag\":false," +
				"\"fullName\":\"Energistics.Etp.v12.Protocol.GrowingObjectNotification.SubscribePart" +
				"Notifications\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.Object.Subscription" +
				"Info\"\r\n]}");
		private IDictionary<string,Energistics.Etp.v12.Datatypes.Object.SubscriptionInfo> _request;
		public virtual Schema Schema
		{
			get
			{
				return SubscribePartNotifications._SCHEMA;
			}
		}
		public IDictionary<string,Energistics.Etp.v12.Datatypes.Object.SubscriptionInfo> Request
		{
			get
			{
				return this._request;
			}
			set
			{
				this._request = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._request;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._request = (IDictionary<string,Energistics.Etp.v12.Datatypes.Object.SubscriptionInfo>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
