// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.GrowingObjectNotification
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class UnsolicitedPartNotifications : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"UnsolicitedPartNotifications\",\"namespace\":\"Energistics.E" +
				"tp.v12.Protocol.GrowingObjectNotification\",\"fields\":[{\"name\":\"subscriptions\",\"ty" +
				"pe\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"SubscriptionInfo\",\"namespac" +
				"e\":\"Energistics.Etp.v12.Datatypes.Object\",\"fields\":[{\"name\":\"context\",\"type\":{\"t" +
				"ype\":\"record\",\"name\":\"ContextInfo\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Ob" +
				"ject\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{\"name\":\"depth\",\"type\":\"int\"},{\"n" +
				"ame\":\"dataObjectTypes\",\"default\":[],\"type\":{\"type\":\"array\",\"items\":\"string\"}}],\"" +
				"fullName\":\"Energistics.Etp.v12.Datatypes.Object.ContextInfo\",\"depends\":[]}},{\"na" +
				"me\":\"scope\",\"type\":{\"type\":\"enum\",\"name\":\"ContextScopeKind\",\"namespace\":\"Energis" +
				"tics.Etp.v12.Datatypes.Object\",\"symbols\":[\"self\",\"sources\",\"targets\",\"sourcesOrS" +
				"elf\",\"targetsOrSelf\"],\"fullName\":\"Energistics.Etp.v12.Datatypes.Object.ContextSc" +
				"opeKind\",\"depends\":[]}},{\"name\":\"requestUuid\",\"type\":{\"type\":\"fixed\",\"name\":\"Uui" +
				"d\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"size\":16,\"fullName\":\"Energistics" +
				".Etp.v12.Datatypes.Uuid\",\"depends\":[]}},{\"name\":\"startTime\",\"type\":\"long\"},{\"nam" +
				"e\":\"includeObjectData\",\"type\":\"boolean\"},{\"name\":\"format\",\"default\":\"xml\",\"type\"" +
				":\"string\"}],\"fullName\":\"Energistics.Etp.v12.Datatypes.Object.SubscriptionInfo\",\"" +
				"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.Object.ContextInfo\",\r\n  \"Energistic" +
				"s.Etp.v12.Datatypes.Object.ContextScopeKind\",\r\n  \"Energistics.Etp.v12.Datatypes." +
				"Uuid\"\r\n]}}}],\"protocol\":\"7\",\"messageType\":\"9\",\"senderRole\":\"store\",\"protocolRole" +
				"s\":\"store,customer\",\"multipartFlag\":false,\"fullName\":\"Energistics.Etp.v12.Protoc" +
				"ol.GrowingObjectNotification.UnsolicitedPartNotifications\",\"depends\":[\r\n  \"Energ" +
				"istics.Etp.v12.Datatypes.Object.SubscriptionInfo\"\r\n]}");
		private IList<Energistics.Etp.v12.Datatypes.Object.SubscriptionInfo> _subscriptions;
		public virtual Schema Schema
		{
			get
			{
				return UnsolicitedPartNotifications._SCHEMA;
			}
		}
		public IList<Energistics.Etp.v12.Datatypes.Object.SubscriptionInfo> Subscriptions
		{
			get
			{
				return this._subscriptions;
			}
			set
			{
				this._subscriptions = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._subscriptions;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._subscriptions = (IList<Energistics.Etp.v12.Datatypes.Object.SubscriptionInfo>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
