// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v11.Protocol.DataArray
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class PutDataArray : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"PutDataArray\",\"namespace\":\"Energistics.Protocol.DataArra" +
				"y\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{\"name\":\"data\",\"type\":{\"type\":\"recor" +
				"d\",\"name\":\"AnyArray\",\"namespace\":\"Energistics.Datatypes\",\"fields\":[{\"name\":\"item" +
				"\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"ArrayOfBoolean\",\"namespace\":\"Energisti" +
				"cs.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"boolean" +
				"\"}}],\"fullName\":\"Energistics.Datatypes.ArrayOfBoolean\",\"depends\":[]},\"bytes\",{\"t" +
				"ype\":\"record\",\"name\":\"ArrayOfInt\",\"namespace\":\"Energistics.Datatypes\",\"fields\":[" +
				"{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"int\"}}],\"fullName\":\"Energistics" +
				".Datatypes.ArrayOfInt\",\"depends\":[]},{\"type\":\"record\",\"name\":\"ArrayOfLong\",\"name" +
				"space\":\"Energistics.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\"" +
				",\"items\":\"long\"}}],\"fullName\":\"Energistics.Datatypes.ArrayOfLong\",\"depends\":[]}," +
				"{\"type\":\"record\",\"name\":\"ArrayOfFloat\",\"namespace\":\"Energistics.Datatypes\",\"fiel" +
				"ds\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"float\"}}],\"fullName\":\"Ener" +
				"gistics.Datatypes.ArrayOfFloat\",\"depends\":[]},{\"type\":\"record\",\"name\":\"ArrayOfDo" +
				"uble\",\"namespace\":\"Energistics.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"ty" +
				"pe\":\"array\",\"items\":\"double\"}}],\"fullName\":\"Energistics.Datatypes.ArrayOfDouble\"" +
				",\"depends\":[]}]}],\"fullName\":\"Energistics.Datatypes.AnyArray\",\"depends\":[\r\n  \"En" +
				"ergistics.Datatypes.ArrayOfBoolean\",\r\n  \"Energistics.Datatypes.ArrayOfInt\",\r\n  \"" +
				"Energistics.Datatypes.ArrayOfLong\",\r\n  \"Energistics.Datatypes.ArrayOfFloat\",\r\n  " +
				"\"Energistics.Datatypes.ArrayOfDouble\"\r\n]}},{\"name\":\"dimensions\",\"type\":{\"type\":\"" +
				"array\",\"items\":\"long\"}}],\"messageType\":\"4\",\"protocol\":\"7\",\"senderRole\":\"customer" +
				"\",\"protocolRoles\":\"store,customer\",\"fullName\":\"Energistics.Protocol.DataArray.Pu" +
				"tDataArray\",\"depends\":[\r\n  \"Energistics.Datatypes.AnyArray\"\r\n]}");
		private string _uri;
		private Energistics.Etp.v11.Datatypes.AnyArray _data;
		private IList<System.Int64> _dimensions;
		public virtual Schema Schema
		{
			get
			{
				return PutDataArray._SCHEMA;
			}
		}
		public string Uri
		{
			get
			{
				return this._uri;
			}
			set
			{
				this._uri = value;
			}
		}
		public Energistics.Etp.v11.Datatypes.AnyArray Data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
		public IList<System.Int64> Dimensions
		{
			get
			{
				return this._dimensions;
			}
			set
			{
				this._dimensions = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._uri;
			case 1: return this._data;
			case 2: return this._dimensions;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._uri = (System.String)fieldValue; break;
			case 1: this._data = (Energistics.Etp.v11.Datatypes.AnyArray)fieldValue; break;
			case 2: this._dimensions = (IList<System.Int64>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
