// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v11.Protocol.DataArray
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class PutDataArraySlice : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"PutDataArraySlice\",\"namespace\":\"Energistics.Protocol.Dat" +
				"aArray\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{\"name\":\"data\",\"type\":{\"type\":\"" +
				"record\",\"name\":\"AnyArray\",\"namespace\":\"Energistics.Datatypes\",\"fields\":[{\"name\":" +
				"\"item\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"ArrayOfBoolean\",\"namespace\":\"Ener" +
				"gistics.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"bo" +
				"olean\"}}],\"fullName\":\"Energistics.Datatypes.ArrayOfBoolean\",\"depends\":[]},\"bytes" +
				"\",{\"type\":\"record\",\"name\":\"ArrayOfInt\",\"namespace\":\"Energistics.Datatypes\",\"fiel" +
				"ds\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"int\"}}],\"fullName\":\"Energi" +
				"stics.Datatypes.ArrayOfInt\",\"depends\":[]},{\"type\":\"record\",\"name\":\"ArrayOfLong\"," +
				"\"namespace\":\"Energistics.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"a" +
				"rray\",\"items\":\"long\"}}],\"fullName\":\"Energistics.Datatypes.ArrayOfLong\",\"depends\"" +
				":[]},{\"type\":\"record\",\"name\":\"ArrayOfFloat\",\"namespace\":\"Energistics.Datatypes\"," +
				"\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"float\"}}],\"fullName\":" +
				"\"Energistics.Datatypes.ArrayOfFloat\",\"depends\":[]},{\"type\":\"record\",\"name\":\"Arra" +
				"yOfDouble\",\"namespace\":\"Energistics.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\"" +
				":{\"type\":\"array\",\"items\":\"double\"}}],\"fullName\":\"Energistics.Datatypes.ArrayOfDo" +
				"uble\",\"depends\":[]}]}],\"fullName\":\"Energistics.Datatypes.AnyArray\",\"depends\":[\r\n" +
				"  \"Energistics.Datatypes.ArrayOfBoolean\",\r\n  \"Energistics.Datatypes.ArrayOfInt\"," +
				"\r\n  \"Energistics.Datatypes.ArrayOfLong\",\r\n  \"Energistics.Datatypes.ArrayOfFloat\"" +
				",\r\n  \"Energistics.Datatypes.ArrayOfDouble\"\r\n]}},{\"name\":\"dimensions\",\"type\":{\"ty" +
				"pe\":\"array\",\"items\":\"long\"}},{\"name\":\"start\",\"type\":{\"type\":\"array\",\"items\":\"lon" +
				"g\"}},{\"name\":\"count\",\"type\":{\"type\":\"array\",\"items\":\"long\"}}],\"messageType\":\"5\"," +
				"\"protocol\":\"7\",\"senderRole\":\"customer\",\"protocolRoles\":\"store,customer\",\"fullNam" +
				"e\":\"Energistics.Protocol.DataArray.PutDataArraySlice\",\"depends\":[\r\n  \"Energistic" +
				"s.Datatypes.AnyArray\"\r\n]}");
		private string _uri;
		private Energistics.Etp.v11.Datatypes.AnyArray _data;
		private IList<System.Int64> _dimensions;
		private IList<System.Int64> _start;
		private IList<System.Int64> _count;
		public virtual Schema Schema
		{
			get
			{
				return PutDataArraySlice._SCHEMA;
			}
		}
		public string Uri
		{
			get
			{
				return this._uri;
			}
			set
			{
				this._uri = value;
			}
		}
		public Energistics.Etp.v11.Datatypes.AnyArray Data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
		public IList<System.Int64> Dimensions
		{
			get
			{
				return this._dimensions;
			}
			set
			{
				this._dimensions = value;
			}
		}
		public IList<System.Int64> Start
		{
			get
			{
				return this._start;
			}
			set
			{
				this._start = value;
			}
		}
		public IList<System.Int64> Count
		{
			get
			{
				return this._count;
			}
			set
			{
				this._count = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._uri;
			case 1: return this._data;
			case 2: return this._dimensions;
			case 3: return this._start;
			case 4: return this._count;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._uri = (System.String)fieldValue; break;
			case 1: this._data = (Energistics.Etp.v11.Datatypes.AnyArray)fieldValue; break;
			case 2: this._dimensions = (IList<System.Int64>)fieldValue; break;
			case 3: this._start = (IList<System.Int64>)fieldValue; break;
			case 4: this._count = (IList<System.Int64>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
