// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v11.Protocol.Store
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class PutObject : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""PutObject"",""namespace"":""Energistics.Protocol.Store"",""fields"":[{""name"":""dataObject"",""type"":{""type"":""record"",""name"":""DataObject"",""namespace"":""Energistics.Datatypes.Object"",""fields"":[{""name"":""resource"",""type"":{""type"":""record"",""name"":""Resource"",""namespace"":""Energistics.Datatypes.Object"",""fields"":[{""name"":""uri"",""type"":""string""},{""name"":""contentType"",""type"":""string""},{""name"":""name"",""type"":""string""},{""name"":""channelSubscribable"",""type"":""boolean""},{""name"":""customData"",""type"":{""type"":""map"",""values"":""string""}},{""name"":""resourceType"",""type"":""string""},{""name"":""hasChildren"",""type"":""int""},{""name"":""uuid"",""type"":[""null"",""string""]},{""name"":""lastChanged"",""type"":""long""},{""name"":""objectNotifiable"",""type"":""boolean""}],""fullName"":""Energistics.Datatypes.Object.Resource"",""depends"":[]}},{""name"":""contentEncoding"",""type"":""string""},{""name"":""data"",""type"":""bytes""}],""fullName"":""Energistics.Datatypes.Object.DataObject"",""depends"":[
  ""Energistics.Datatypes.Object.Resource""
]}}],""messageType"":""2"",""protocol"":""4"",""senderRole"":""customer"",""protocolRoles"":""store,customer"",""fullName"":""Energistics.Protocol.Store.PutObject"",""depends"":[
  ""Energistics.Datatypes.Object.DataObject""
]}");
		private Energistics.Etp.v11.Datatypes.Object.DataObject _dataObject;
		public virtual Schema Schema
		{
			get
			{
				return PutObject._SCHEMA;
			}
		}
		public Energistics.Etp.v11.Datatypes.Object.DataObject DataObject
		{
			get
			{
				return this._dataObject;
			}
			set
			{
				this._dataObject = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._dataObject;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._dataObject = (Energistics.Etp.v11.Datatypes.Object.DataObject)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
