// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Energistics.Etp.Common.Datatypes.DataArrayTypes
{
    public interface IDataArray
    {
        IAnyArray Data { get; set; }

        IList<long> Dimensions { get; set; }
    }
}