// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.Core
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class CloseSession : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""CloseSession"",""namespace"":""Energistics.Etp.v12.Protocol.Core"",""fields"":[{""name"":""reason"",""default"":"""",""type"":""string""}],""protocol"":""0"",""messageType"":""5"",""senderRole"":""client,server"",""protocolRoles"":""client, server"",""multipartFlag"":false,""fullName"":""Energistics.Etp.v12.Protocol.Core.CloseSession"",""depends"":[]}");
		private string _reason;
		public virtual Schema Schema
		{
			get
			{
				return CloseSession._SCHEMA;
			}
		}
		public string Reason
		{
			get
			{
				return this._reason;
			}
			set
			{
				this._reason = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._reason;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._reason = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
