// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.Store
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class PutDataObjects : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"PutDataObjects\",\"namespace\":\"Energistics.Etp.v12.Protoco" +
				"l.Store\",\"fields\":[{\"name\":\"dataObjects\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"" +
				"record\",\"name\":\"DataObject\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Object\",\"" +
				"fields\":[{\"name\":\"resource\",\"type\":{\"type\":\"record\",\"name\":\"Resource\",\"namespace" +
				"\":\"Energistics.Etp.v12.Datatypes.Object\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"" +
				"},{\"name\":\"alternateUris\",\"default\":[],\"type\":{\"type\":\"array\",\"items\":\"string\"}}" +
				",{\"name\":\"dataObjectType\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"nam" +
				"e\":\"sourceCount\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"targetCount\",\"de" +
				"fault\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"lastChanged\",\"type\":\"long\"},{\"name\":" +
				"\"customData\",\"default\":{},\"type\":{\"type\":\"map\",\"values\":\"string\"}}],\"fullName\":\"" +
				"Energistics.Etp.v12.Datatypes.Object.Resource\",\"depends\":[]}},{\"name\":\"format\",\"" +
				"default\":\"xml\",\"type\":\"string\"},{\"name\":\"blobId\",\"type\":[\"null\",{\"type\":\"fixed\"," +
				"\"name\":\"Uuid\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"size\":16,\"fullName\":\"" +
				"Energistics.Etp.v12.Datatypes.Uuid\",\"depends\":[]}]},{\"name\":\"data\",\"default\":\"\"," +
				"\"type\":\"bytes\"}],\"fullName\":\"Energistics.Etp.v12.Datatypes.Object.DataObject\",\"d" +
				"epends\":[\r\n  \"Energistics.Etp.v12.Datatypes.Object.Resource\",\r\n  \"Energistics.Et" +
				"p.v12.Datatypes.Uuid\"\r\n]}}}],\"protocol\":\"4\",\"messageType\":\"2\",\"senderRole\":\"cust" +
				"omer\",\"protocolRoles\":\"store,customer\",\"multipartFlag\":false,\"fullName\":\"Energis" +
				"tics.Etp.v12.Protocol.Store.PutDataObjects\",\"depends\":[\r\n  \"Energistics.Etp.v12." +
				"Datatypes.Object.DataObject\"\r\n]}");
		private IDictionary<string,Energistics.Etp.v12.Datatypes.Object.DataObject> _dataObjects;
		public virtual Schema Schema
		{
			get
			{
				return PutDataObjects._SCHEMA;
			}
		}
		public IDictionary<string,Energistics.Etp.v12.Datatypes.Object.DataObject> DataObjects
		{
			get
			{
				return this._dataObjects;
			}
			set
			{
				this._dataObjects = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._dataObjects;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._dataObjects = (IDictionary<string,Energistics.Etp.v12.Datatypes.Object.DataObject>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
