// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes.ChannelData
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class ChannelMetadataRecord : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ChannelMetadataRecord\",\"namespace\":\"Energistics.Etp.v12." +
				"Datatypes.ChannelData\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{\"name\":\"id\",\"ty" +
				"pe\":\"long\"},{\"name\":\"indexes\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"n" +
				"ame\":\"IndexMetadataRecord\",\"namespace\":\"Energistics.Etp.v12.Datatypes.ChannelDat" +
				"a\",\"fields\":[{\"name\":\"indexKind\",\"default\":\"Time\",\"type\":{\"type\":\"enum\",\"name\":\"" +
				"ChannelIndexKind\",\"namespace\":\"Energistics.Etp.v12.Datatypes.ChannelData\",\"symbo" +
				"ls\":[\"Time\",\"Depth\",\"Scalar\",\"ElapsedTime\"],\"fullName\":\"Energistics.Etp.v12.Data" +
				"types.ChannelData.ChannelIndexKind\",\"depends\":[]}},{\"name\":\"interval\",\"type\":{\"t" +
				"ype\":\"record\",\"name\":\"IndexInterval\",\"namespace\":\"Energistics.Etp.v12.Datatypes." +
				"Object\",\"fields\":[{\"name\":\"startIndex\",\"type\":{\"type\":\"record\",\"name\":\"IndexValu" +
				"e\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"item\",\"type\":[" +
				"\"null\",\"long\",\"double\"]}],\"fullName\":\"Energistics.Etp.v12.Datatypes.IndexValue\"," +
				"\"depends\":[]}},{\"name\":\"endIndex\",\"type\":\"Energistics.Etp.v12.Datatypes.IndexVal" +
				"ue\"},{\"name\":\"uom\",\"type\":\"string\"},{\"name\":\"depthDatum\",\"default\":\"\",\"type\":\"st" +
				"ring\"}],\"fullName\":\"Energistics.Etp.v12.Datatypes.Object.IndexInterval\",\"depends" +
				"\":[\r\n  \"Energistics.Etp.v12.Datatypes.IndexValue\",\r\n  \"Energistics.Etp.v12.Datat" +
				"ypes.IndexValue\"\r\n]}},{\"name\":\"direction\",\"default\":\"Increasing\",\"type\":{\"type\":" +
				"\"enum\",\"name\":\"IndexDirection\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Channe" +
				"lData\",\"symbols\":[\"Increasing\",\"Decreasing\"],\"fullName\":\"Energistics.Etp.v12.Dat" +
				"atypes.ChannelData.IndexDirection\",\"depends\":[]}},{\"name\":\"name\",\"default\":\"\",\"t" +
				"ype\":\"string\"}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ChannelData.IndexMetad" +
				"ataRecord\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.ChannelData.ChannelInde" +
				"xKind\",\r\n  \"Energistics.Etp.v12.Datatypes.Object.IndexInterval\",\r\n  \"Energistics" +
				".Etp.v12.Datatypes.ChannelData.IndexDirection\"\r\n]}}},{\"name\":\"channelName\",\"type" +
				"\":\"string\"},{\"name\":\"dataType\",\"type\":{\"type\":\"enum\",\"name\":\"DataValueType\",\"nam" +
				"espace\":\"Energistics.Etp.v12.Datatypes\",\"symbols\":[\"typeBoolean\",\"typeInt\",\"type" +
				"Long\",\"typeFloat\",\"typeDouble\",\"typeString\",\"typeArrayOfBoolean\",\"typeArrayOfInt" +
				"\",\"typeArrayOfLong\",\"typeArrayOfFloat\",\"typeArrayOfDouble\",\"typeArrayOfString\",\"" +
				"typeBytes\"],\"fullName\":\"Energistics.Etp.v12.Datatypes.DataValueType\",\"depends\":[" +
				"]}},{\"name\":\"uom\",\"type\":\"string\"},{\"name\":\"measureClass\",\"type\":\"string\"},{\"nam" +
				"e\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"ActiveStatusKind\",\"namespace\":\"Energis" +
				"tics.Etp.v12.Datatypes.Object\",\"symbols\":[\"Active\",\"Inactive\"],\"fullName\":\"Energ" +
				"istics.Etp.v12.Datatypes.Object.ActiveStatusKind\",\"depends\":[]}},{\"name\":\"source" +
				"\",\"type\":\"string\"},{\"name\":\"axisVectorLengths\",\"type\":{\"type\":\"array\",\"items\":\"i" +
				"nt\"}},{\"name\":\"customData\",\"default\":{},\"type\":{\"type\":\"map\",\"values\":{\"type\":\"r" +
				"ecord\",\"name\":\"DataValue\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[" +
				"{\"name\":\"item\",\"type\":[\"null\",\"boolean\",\"int\",\"long\",\"float\",\"double\",\"string\",{" +
				"\"type\":\"record\",\"name\":\"ArrayOfBoolean\",\"namespace\":\"Energistics.Etp.v12.Datatyp" +
				"es\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"boolean\"}}],\"full" +
				"Name\":\"Energistics.Etp.v12.Datatypes.ArrayOfBoolean\",\"depends\":[]},{\"type\":\"reco" +
				"rd\",\"name\":\"ArrayOfNullableBoolean\",\"namespace\":\"Energistics.Etp.v12.Datatypes\"," +
				"\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":[\"null\",\"boolean\"]}}]," +
				"\"fullName\":\"Energistics.Etp.v12.Datatypes.ArrayOfNullableBoolean\",\"depends\":[]}," +
				"{\"type\":\"record\",\"name\":\"ArrayOfInt\",\"namespace\":\"Energistics.Etp.v12.Datatypes\"" +
				",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"int\"}}],\"fullName\":\"" +
				"Energistics.Etp.v12.Datatypes.ArrayOfInt\",\"depends\":[]},{\"type\":\"record\",\"name\":" +
				"\"ArrayOfNullableInt\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"nam" +
				"e\":\"values\",\"type\":{\"type\":\"array\",\"items\":[\"null\",\"int\"]}}],\"fullName\":\"Energis" +
				"tics.Etp.v12.Datatypes.ArrayOfNullableInt\",\"depends\":[]},{\"type\":\"record\",\"name\"" +
				":\"ArrayOfLong\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"va" +
				"lues\",\"type\":{\"type\":\"array\",\"items\":\"long\"}}],\"fullName\":\"Energistics.Etp.v12.D" +
				"atatypes.ArrayOfLong\",\"depends\":[]},{\"type\":\"record\",\"name\":\"ArrayOfNullableLong" +
				"\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":" +
				"{\"type\":\"array\",\"items\":[\"null\",\"long\"]}}],\"fullName\":\"Energistics.Etp.v12.Datat" +
				"ypes.ArrayOfNullableLong\",\"depends\":[]},{\"type\":\"record\",\"name\":\"ArrayOfFloat\",\"" +
				"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"t" +
				"ype\":\"array\",\"items\":\"float\"}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ArrayO" +
				"fFloat\",\"depends\":[]},{\"type\":\"record\",\"name\":\"ArrayOfDouble\",\"namespace\":\"Energ" +
				"istics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"ite" +
				"ms\":\"double\"}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ArrayOfDouble\",\"depend" +
				"s\":[]},{\"type\":\"record\",\"name\":\"ArrayOfString\",\"namespace\":\"Energistics.Etp.v12." +
				"Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]" +
				",\"fullName\":\"Energistics.Etp.v12.Datatypes.ArrayOfString\",\"depends\":[]},\"bytes\"," +
				"{\"type\":\"record\",\"name\":\"AnySparseArray\",\"namespace\":\"Energistics.Etp.v12.Dataty" +
				"pes\",\"fields\":[{\"name\":\"slices\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\"," +
				"\"name\":\"AnySubarray\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"nam" +
				"e\":\"start\",\"type\":\"long\"},{\"name\":\"slice\",\"type\":{\"type\":\"record\",\"name\":\"AnyArr" +
				"ay\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"item\",\"type\":" +
				"[\"ArrayOfBoolean\",\"ArrayOfInt\",\"ArrayOfLong\",\"ArrayOfFloat\",\"ArrayOfDouble\",\"Arr" +
				"ayOfString\",\"bytes\"]}],\"fullName\":\"Energistics.Etp.v12.Datatypes.AnyArray\",\"depe" +
				"nds\":[\r\n  \"Energistics.Etp.v12.Datatypes.ArrayOfBoolean\",\r\n  \"Energistics.Etp.v1" +
				"2.Datatypes.ArrayOfInt\",\r\n  \"Energistics.Etp.v12.Datatypes.ArrayOfLong\",\r\n  \"Ene" +
				"rgistics.Etp.v12.Datatypes.ArrayOfFloat\",\r\n  \"Energistics.Etp.v12.Datatypes.Arra" +
				"yOfDouble\",\r\n  \"Energistics.Etp.v12.Datatypes.ArrayOfString\"\r\n]}}],\"fullName\":\"E" +
				"nergistics.Etp.v12.Datatypes.AnySubarray\",\"depends\":[\r\n  \"Energistics.Etp.v12.Da" +
				"tatypes.AnyArray\"\r\n]}}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.AnySparseArra" +
				"y\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.AnySubarray\"\r\n]}]}],\"fullName\":" +
				"\"Energistics.Etp.v12.Datatypes.DataValue\",\"depends\":[\r\n  \"Energistics.Etp.v12.Da" +
				"tatypes.ArrayOfBoolean\",\r\n  \"Energistics.Etp.v12.Datatypes.ArrayOfNullableBoolea" +
				"n\",\r\n  \"Energistics.Etp.v12.Datatypes.ArrayOfInt\",\r\n  \"Energistics.Etp.v12.Datat" +
				"ypes.ArrayOfNullableInt\",\r\n  \"Energistics.Etp.v12.Datatypes.ArrayOfLong\",\r\n  \"En" +
				"ergistics.Etp.v12.Datatypes.ArrayOfNullableLong\",\r\n  \"Energistics.Etp.v12.Dataty" +
				"pes.ArrayOfFloat\",\r\n  \"Energistics.Etp.v12.Datatypes.ArrayOfDouble\",\r\n  \"Energis" +
				"tics.Etp.v12.Datatypes.ArrayOfString\",\r\n  \"Energistics.Etp.v12.Datatypes.AnySpar" +
				"seArray\"\r\n]}}},{\"name\":\"attributeMetadata\",\"default\":[],\"type\":{\"type\":\"array\",\"" +
				"items\":{\"type\":\"record\",\"name\":\"AttributeMetadataRecord\",\"namespace\":\"Energistic" +
				"s.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"attributeId\",\"type\":\"int\"},{\"name\":\"attr" +
				"ibuteName\",\"type\":\"string\"},{\"name\":\"dataType\",\"type\":\"DataValueType\"},{\"name\":\"" +
				"description\",\"type\":\"string\"}],\"fullName\":\"Energistics.Etp.v12.Datatypes.Attribu" +
				"teMetadataRecord\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.DataValueType\"\r\n" +
				"]}}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ChannelData.ChannelMetadataRecor" +
				"d\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.ChannelData.IndexMetadataRecord" +
				"\",\r\n  \"Energistics.Etp.v12.Datatypes.DataValueType\",\r\n  \"Energistics.Etp.v12.Dat" +
				"atypes.Object.ActiveStatusKind\",\r\n  \"Energistics.Etp.v12.Datatypes.DataValue\",\r\n" +
				"  \"Energistics.Etp.v12.Datatypes.AttributeMetadataRecord\"\r\n]}");
		private string _uri;
		private long _id;
		private IList<Energistics.Etp.v12.Datatypes.ChannelData.IndexMetadataRecord> _indexes;
		private string _channelName;
		private Energistics.Etp.v12.Datatypes.DataValueType _dataType;
		private string _uom;
		private string _measureClass;
		private Energistics.Etp.v12.Datatypes.Object.ActiveStatusKind _status;
		private string _source;
		private IList<System.Int32> _axisVectorLengths;
		private IDictionary<string,Energistics.Etp.v12.Datatypes.DataValue> _customData;
		private IList<Energistics.Etp.v12.Datatypes.AttributeMetadataRecord> _attributeMetadata;
		public virtual Schema Schema
		{
			get
			{
				return ChannelMetadataRecord._SCHEMA;
			}
		}
		public string Uri
		{
			get
			{
				return this._uri;
			}
			set
			{
				this._uri = value;
			}
		}
		public long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public IList<Energistics.Etp.v12.Datatypes.ChannelData.IndexMetadataRecord> Indexes
		{
			get
			{
				return this._indexes;
			}
			set
			{
				this._indexes = value;
			}
		}
		public string ChannelName
		{
			get
			{
				return this._channelName;
			}
			set
			{
				this._channelName = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.DataValueType DataType
		{
			get
			{
				return this._dataType;
			}
			set
			{
				this._dataType = value;
			}
		}
		public string Uom
		{
			get
			{
				return this._uom;
			}
			set
			{
				this._uom = value;
			}
		}
		public string MeasureClass
		{
			get
			{
				return this._measureClass;
			}
			set
			{
				this._measureClass = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.Object.ActiveStatusKind Status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		public string Source
		{
			get
			{
				return this._source;
			}
			set
			{
				this._source = value;
			}
		}
		public IList<System.Int32> AxisVectorLengths
		{
			get
			{
				return this._axisVectorLengths;
			}
			set
			{
				this._axisVectorLengths = value;
			}
		}
		public IDictionary<string,Energistics.Etp.v12.Datatypes.DataValue> CustomData
		{
			get
			{
				return this._customData;
			}
			set
			{
				this._customData = value;
			}
		}
		public IList<Energistics.Etp.v12.Datatypes.AttributeMetadataRecord> AttributeMetadata
		{
			get
			{
				return this._attributeMetadata;
			}
			set
			{
				this._attributeMetadata = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._uri;
			case 1: return this._id;
			case 2: return this._indexes;
			case 3: return this._channelName;
			case 4: return this._dataType;
			case 5: return this._uom;
			case 6: return this._measureClass;
			case 7: return this._status;
			case 8: return this._source;
			case 9: return this._axisVectorLengths;
			case 10: return this._customData;
			case 11: return this._attributeMetadata;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._uri = (System.String)fieldValue; break;
			case 1: this._id = (System.Int64)fieldValue; break;
			case 2: this._indexes = (IList<Energistics.Etp.v12.Datatypes.ChannelData.IndexMetadataRecord>)fieldValue; break;
			case 3: this._channelName = (System.String)fieldValue; break;
			case 4: this._dataType = (Energistics.Etp.v12.Datatypes.DataValueType)fieldValue; break;
			case 5: this._uom = (System.String)fieldValue; break;
			case 6: this._measureClass = (System.String)fieldValue; break;
			case 7: this._status = (Energistics.Etp.v12.Datatypes.Object.ActiveStatusKind)fieldValue; break;
			case 8: this._source = (System.String)fieldValue; break;
			case 9: this._axisVectorLengths = (IList<System.Int32>)fieldValue; break;
			case 10: this._customData = (IDictionary<string,Energistics.Etp.v12.Datatypes.DataValue>)fieldValue; break;
			case 11: this._attributeMetadata = (IList<Energistics.Etp.v12.Datatypes.AttributeMetadataRecord>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
