// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes.ChannelData
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class ChannelChangeResponseInfo : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""ChannelChangeResponseInfo"",""namespace"":""Energistics.Etp.v12.Datatypes.ChannelData"",""fields"":[{""name"":""responseTimestamp"",""type"":""long""},{""name"":""channelChanges"",""type"":{""type"":""map"",""values"":{""type"":""array"",""items"":{""type"":""record"",""name"":""ChannelChangeAnnotation"",""namespace"":""Energistics.Etp.v12.Datatypes.ChannelData"",""fields"":[{""name"":""changeTime"",""type"":""long""},{""name"":""interval"",""type"":{""type"":""record"",""name"":""IndexInterval"",""namespace"":""Energistics.Etp.v12.Datatypes.Object"",""fields"":[{""name"":""startIndex"",""type"":{""type"":""record"",""name"":""IndexValue"",""namespace"":""Energistics.Etp.v12.Datatypes"",""fields"":[{""name"":""item"",""type"":[""null"",""long"",""double""]}],""fullName"":""Energistics.Etp.v12.Datatypes.IndexValue"",""depends"":[]}},{""name"":""endIndex"",""type"":""Energistics.Etp.v12.Datatypes.IndexValue""},{""name"":""uom"",""type"":""string""},{""name"":""depthDatum"",""default"":"""",""type"":""string""}],""fullName"":""Energistics.Etp.v12.Datatypes.Object.IndexInterval"",""depends"":[
  ""Energistics.Etp.v12.Datatypes.IndexValue"",
  ""Energistics.Etp.v12.Datatypes.IndexValue""
]}}],""fullName"":""Energistics.Etp.v12.Datatypes.ChannelData.ChannelChangeAnnotation"",""depends"":[
  ""Energistics.Etp.v12.Datatypes.Object.IndexInterval""
]}}}}],""fullName"":""Energistics.Etp.v12.Datatypes.ChannelData.ChannelChangeResponseInfo"",""depends"":[
  ""Energistics.Etp.v12.Datatypes.ChannelData.ChannelChangeAnnotation""
]}");
		private long _responseTimestamp;
		private IDictionary<string,IList<Energistics.Etp.v12.Datatypes.ChannelData.ChannelChangeAnnotation>> _channelChanges;
		public virtual Schema Schema
		{
			get
			{
				return ChannelChangeResponseInfo._SCHEMA;
			}
		}
		public long ResponseTimestamp
		{
			get
			{
				return this._responseTimestamp;
			}
			set
			{
				this._responseTimestamp = value;
			}
		}
		public IDictionary<string,IList<Energistics.Etp.v12.Datatypes.ChannelData.ChannelChangeAnnotation>> ChannelChanges
		{
			get
			{
				return this._channelChanges;
			}
			set
			{
				this._channelChanges = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._responseTimestamp;
			case 1: return this._channelChanges;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._responseTimestamp = (System.Int64)fieldValue; break;
			case 1: this._channelChanges = (IDictionary<string,IList<Energistics.Etp.v12.Datatypes.ChannelData.ChannelChangeAnnotation>>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
