// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes.ChannelData
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class FrameChannelMetadataRecord : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"FrameChannelMetadataRecord\",\"namespace\":\"Energistics.Etp" +
				".v12.Datatypes.ChannelData\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{\"name\":\"ch" +
				"annelName\",\"type\":\"string\"},{\"name\":\"dataType\",\"type\":{\"type\":\"enum\",\"name\":\"Dat" +
				"aValueType\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"symbols\":[\"typeBoolean\"" +
				",\"typeInt\",\"typeLong\",\"typeFloat\",\"typeDouble\",\"typeString\",\"typeArrayOfBoolean\"" +
				",\"typeArrayOfInt\",\"typeArrayOfLong\",\"typeArrayOfFloat\",\"typeArrayOfDouble\",\"type" +
				"ArrayOfString\",\"typeBytes\"],\"fullName\":\"Energistics.Etp.v12.Datatypes.DataValueT" +
				"ype\",\"depends\":[]}},{\"name\":\"uom\",\"type\":\"string\"},{\"name\":\"measureClass\",\"type\"" +
				":\"string\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"ActiveStatusKind\",\"nam" +
				"espace\":\"Energistics.Etp.v12.Datatypes.Object\",\"symbols\":[\"Active\",\"Inactive\"],\"" +
				"fullName\":\"Energistics.Etp.v12.Datatypes.Object.ActiveStatusKind\",\"depends\":[]}}" +
				",{\"name\":\"source\",\"type\":\"string\"},{\"name\":\"axisVectorLengths\",\"type\":{\"type\":\"a" +
				"rray\",\"items\":\"int\"}},{\"name\":\"customData\",\"default\":{},\"type\":{\"type\":\"map\",\"va" +
				"lues\":{\"type\":\"record\",\"name\":\"DataValue\",\"namespace\":\"Energistics.Etp.v12.Datat" +
				"ypes\",\"fields\":[{\"name\":\"item\",\"type\":[\"null\",\"boolean\",\"int\",\"long\",\"float\",\"do" +
				"uble\",\"string\",{\"type\":\"record\",\"name\":\"ArrayOfBoolean\",\"namespace\":\"Energistics" +
				".Etp.v12.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"b" +
				"oolean\"}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ArrayOfBoolean\",\"depends\":[" +
				"]},{\"type\":\"record\",\"name\":\"ArrayOfNullableBoolean\",\"namespace\":\"Energistics.Etp" +
				".v12.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":[\"null" +
				"\",\"boolean\"]}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ArrayOfNullableBoolean" +
				"\",\"depends\":[]},{\"type\":\"record\",\"name\":\"ArrayOfInt\",\"namespace\":\"Energistics.Et" +
				"p.v12.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"int\"" +
				"}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ArrayOfInt\",\"depends\":[]},{\"type\":" +
				"\"record\",\"name\":\"ArrayOfNullableInt\",\"namespace\":\"Energistics.Etp.v12.Datatypes\"" +
				",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":[\"null\",\"int\"]}}],\"fu" +
				"llName\":\"Energistics.Etp.v12.Datatypes.ArrayOfNullableInt\",\"depends\":[]},{\"type\"" +
				":\"record\",\"name\":\"ArrayOfLong\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fiel" +
				"ds\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"long\"}}],\"fullName\":\"Energ" +
				"istics.Etp.v12.Datatypes.ArrayOfLong\",\"depends\":[]},{\"type\":\"record\",\"name\":\"Arr" +
				"ayOfNullableLong\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":" +
				"\"values\",\"type\":{\"type\":\"array\",\"items\":[\"null\",\"long\"]}}],\"fullName\":\"Energisti" +
				"cs.Etp.v12.Datatypes.ArrayOfNullableLong\",\"depends\":[]},{\"type\":\"record\",\"name\":" +
				"\"ArrayOfFloat\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"va" +
				"lues\",\"type\":{\"type\":\"array\",\"items\":\"float\"}}],\"fullName\":\"Energistics.Etp.v12." +
				"Datatypes.ArrayOfFloat\",\"depends\":[]},{\"type\":\"record\",\"name\":\"ArrayOfDouble\",\"n" +
				"amespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"ty" +
				"pe\":\"array\",\"items\":\"double\"}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ArrayO" +
				"fDouble\",\"depends\":[]},{\"type\":\"record\",\"name\":\"ArrayOfString\",\"namespace\":\"Ener" +
				"gistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"it" +
				"ems\":\"string\"}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ArrayOfString\",\"depen" +
				"ds\":[]},\"bytes\",{\"type\":\"record\",\"name\":\"AnySparseArray\",\"namespace\":\"Energistic" +
				"s.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"slices\",\"type\":{\"type\":\"array\",\"items\":{" +
				"\"type\":\"record\",\"name\":\"AnySubarray\",\"namespace\":\"Energistics.Etp.v12.Datatypes\"" +
				",\"fields\":[{\"name\":\"start\",\"type\":\"long\"},{\"name\":\"slice\",\"type\":{\"type\":\"record" +
				"\",\"name\":\"AnyArray\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name" +
				"\":\"item\",\"type\":[\"ArrayOfBoolean\",\"ArrayOfInt\",\"ArrayOfLong\",\"ArrayOfFloat\",\"Arr" +
				"ayOfDouble\",\"ArrayOfString\",\"bytes\"]}],\"fullName\":\"Energistics.Etp.v12.Datatypes" +
				".AnyArray\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.ArrayOfBoolean\",\r\n  \"En" +
				"ergistics.Etp.v12.Datatypes.ArrayOfInt\",\r\n  \"Energistics.Etp.v12.Datatypes.Array" +
				"OfLong\",\r\n  \"Energistics.Etp.v12.Datatypes.ArrayOfFloat\",\r\n  \"Energistics.Etp.v1" +
				"2.Datatypes.ArrayOfDouble\",\r\n  \"Energistics.Etp.v12.Datatypes.ArrayOfString\"\r\n]}" +
				"}],\"fullName\":\"Energistics.Etp.v12.Datatypes.AnySubarray\",\"depends\":[\r\n  \"Energi" +
				"stics.Etp.v12.Datatypes.AnyArray\"\r\n]}}}],\"fullName\":\"Energistics.Etp.v12.Datatyp" +
				"es.AnySparseArray\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.AnySubarray\"\r\n]" +
				"}]}],\"fullName\":\"Energistics.Etp.v12.Datatypes.DataValue\",\"depends\":[\r\n  \"Energi" +
				"stics.Etp.v12.Datatypes.ArrayOfBoolean\",\r\n  \"Energistics.Etp.v12.Datatypes.Array" +
				"OfNullableBoolean\",\r\n  \"Energistics.Etp.v12.Datatypes.ArrayOfInt\",\r\n  \"Energisti" +
				"cs.Etp.v12.Datatypes.ArrayOfNullableInt\",\r\n  \"Energistics.Etp.v12.Datatypes.Arra" +
				"yOfLong\",\r\n  \"Energistics.Etp.v12.Datatypes.ArrayOfNullableLong\",\r\n  \"Energistic" +
				"s.Etp.v12.Datatypes.ArrayOfFloat\",\r\n  \"Energistics.Etp.v12.Datatypes.ArrayOfDoub" +
				"le\",\r\n  \"Energistics.Etp.v12.Datatypes.ArrayOfString\",\r\n  \"Energistics.Etp.v12.D" +
				"atatypes.AnySparseArray\"\r\n]}}},{\"name\":\"attributeMetadata\",\"default\":[],\"type\":{" +
				"\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AttributeMetadataRecord\",\"namesp" +
				"ace\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"attributeId\",\"type\":\"int" +
				"\"},{\"name\":\"attributeName\",\"type\":\"string\"},{\"name\":\"dataType\",\"type\":\"DataValue" +
				"Type\"},{\"name\":\"description\",\"type\":\"string\"}],\"fullName\":\"Energistics.Etp.v12.D" +
				"atatypes.AttributeMetadataRecord\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes." +
				"DataValueType\"\r\n]}}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ChannelData.Fram" +
				"eChannelMetadataRecord\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.DataValueT" +
				"ype\",\r\n  \"Energistics.Etp.v12.Datatypes.Object.ActiveStatusKind\",\r\n  \"Energistic" +
				"s.Etp.v12.Datatypes.DataValue\",\r\n  \"Energistics.Etp.v12.Datatypes.AttributeMetad" +
				"ataRecord\"\r\n]}");
		private string _uri;
		private string _channelName;
		private Energistics.Etp.v12.Datatypes.DataValueType _dataType;
		private string _uom;
		private string _measureClass;
		private Energistics.Etp.v12.Datatypes.Object.ActiveStatusKind _status;
		private string _source;
		private IList<System.Int32> _axisVectorLengths;
		private IDictionary<string,Energistics.Etp.v12.Datatypes.DataValue> _customData;
		private IList<Energistics.Etp.v12.Datatypes.AttributeMetadataRecord> _attributeMetadata;
		public virtual Schema Schema
		{
			get
			{
				return FrameChannelMetadataRecord._SCHEMA;
			}
		}
		public string Uri
		{
			get
			{
				return this._uri;
			}
			set
			{
				this._uri = value;
			}
		}
		public string ChannelName
		{
			get
			{
				return this._channelName;
			}
			set
			{
				this._channelName = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.DataValueType DataType
		{
			get
			{
				return this._dataType;
			}
			set
			{
				this._dataType = value;
			}
		}
		public string Uom
		{
			get
			{
				return this._uom;
			}
			set
			{
				this._uom = value;
			}
		}
		public string MeasureClass
		{
			get
			{
				return this._measureClass;
			}
			set
			{
				this._measureClass = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.Object.ActiveStatusKind Status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		public string Source
		{
			get
			{
				return this._source;
			}
			set
			{
				this._source = value;
			}
		}
		public IList<System.Int32> AxisVectorLengths
		{
			get
			{
				return this._axisVectorLengths;
			}
			set
			{
				this._axisVectorLengths = value;
			}
		}
		public IDictionary<string,Energistics.Etp.v12.Datatypes.DataValue> CustomData
		{
			get
			{
				return this._customData;
			}
			set
			{
				this._customData = value;
			}
		}
		public IList<Energistics.Etp.v12.Datatypes.AttributeMetadataRecord> AttributeMetadata
		{
			get
			{
				return this._attributeMetadata;
			}
			set
			{
				this._attributeMetadata = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._uri;
			case 1: return this._channelName;
			case 2: return this._dataType;
			case 3: return this._uom;
			case 4: return this._measureClass;
			case 5: return this._status;
			case 6: return this._source;
			case 7: return this._axisVectorLengths;
			case 8: return this._customData;
			case 9: return this._attributeMetadata;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._uri = (System.String)fieldValue; break;
			case 1: this._channelName = (System.String)fieldValue; break;
			case 2: this._dataType = (Energistics.Etp.v12.Datatypes.DataValueType)fieldValue; break;
			case 3: this._uom = (System.String)fieldValue; break;
			case 4: this._measureClass = (System.String)fieldValue; break;
			case 5: this._status = (Energistics.Etp.v12.Datatypes.Object.ActiveStatusKind)fieldValue; break;
			case 6: this._source = (System.String)fieldValue; break;
			case 7: this._axisVectorLengths = (IList<System.Int32>)fieldValue; break;
			case 8: this._customData = (IDictionary<string,Energistics.Etp.v12.Datatypes.DataValue>)fieldValue; break;
			case 9: this._attributeMetadata = (IList<Energistics.Etp.v12.Datatypes.AttributeMetadataRecord>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
