// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes.ChannelData
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class IndexMetadataRecord : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"IndexMetadataRecord\",\"namespace\":\"Energistics.Etp.v12.Da" +
				"tatypes.ChannelData\",\"fields\":[{\"name\":\"indexKind\",\"default\":\"Time\",\"type\":{\"typ" +
				"e\":\"enum\",\"name\":\"ChannelIndexKinds\",\"namespace\":\"Energistics.Etp.v12.Datatypes." +
				"ChannelData\",\"symbols\":[\"Time\",\"Depth\"],\"fullName\":\"Energistics.Etp.v12.Datatype" +
				"s.ChannelData.ChannelIndexKinds\",\"depends\":[]}},{\"name\":\"uom\",\"type\":\"string\"},{" +
				"\"name\":\"depthDatum\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"direction\",\"default\":" +
				"\"Increasing\",\"type\":{\"type\":\"enum\",\"name\":\"IndexDirections\",\"namespace\":\"Energis" +
				"tics.Etp.v12.Datatypes.ChannelData\",\"symbols\":[\"Increasing\",\"Decreasing\"],\"fullN" +
				"ame\":\"Energistics.Etp.v12.Datatypes.ChannelData.IndexDirections\",\"depends\":[]}}," +
				"{\"name\":\"mnemonic\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"description\",\"default\"" +
				":\"\",\"type\":\"string\"},{\"name\":\"uri\",\"default\":\"\",\"type\":\"string\"},{\"name\":\"custom" +
				"Data\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"record\",\"name\":\"DataValue\",\"namespa" +
				"ce\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"item\",\"type\":[\"null\",\"dou" +
				"ble\",\"float\",\"int\",\"long\",\"string\",{\"type\":\"record\",\"name\":\"ArrayOfDouble\",\"name" +
				"space\":\"Energistics.Etp.v12.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\"" +
				":\"array\",\"items\":\"double\"}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ArrayOfDo" +
				"uble\",\"depends\":[]},\"boolean\",\"bytes\"]}],\"fullName\":\"Energistics.Etp.v12.Datatyp" +
				"es.DataValue\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.ArrayOfDouble\"\r\n]}}}" +
				",{\"name\":\"scale\",\"default\":3,\"type\":\"int\"},{\"name\":\"timeDatum\",\"default\":\"\",\"typ" +
				"e\":\"string\"}],\"fullName\":\"Energistics.Etp.v12.Datatypes.ChannelData.IndexMetadat" +
				"aRecord\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.ChannelData.ChannelIndexK" +
				"inds\",\r\n  \"Energistics.Etp.v12.Datatypes.ChannelData.IndexDirections\",\r\n  \"Energ" +
				"istics.Etp.v12.Datatypes.DataValue\"\r\n]}");
		private Energistics.Etp.v12.Datatypes.ChannelData.ChannelIndexKinds _indexKind;
		private string _uom;
		private string _depthDatum;
		private Energistics.Etp.v12.Datatypes.ChannelData.IndexDirections _direction;
		private string _mnemonic;
		private string _description;
		private string _uri;
		private IDictionary<string,Energistics.Etp.v12.Datatypes.DataValue> _customData;
		private int _scale;
		private string _timeDatum;
		public virtual Schema Schema
		{
			get
			{
				return IndexMetadataRecord._SCHEMA;
			}
		}
		public Energistics.Etp.v12.Datatypes.ChannelData.ChannelIndexKinds IndexKind
		{
			get
			{
				return this._indexKind;
			}
			set
			{
				this._indexKind = value;
			}
		}
		public string Uom
		{
			get
			{
				return this._uom;
			}
			set
			{
				this._uom = value;
			}
		}
		public string DepthDatum
		{
			get
			{
				return this._depthDatum;
			}
			set
			{
				this._depthDatum = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.ChannelData.IndexDirections Direction
		{
			get
			{
				return this._direction;
			}
			set
			{
				this._direction = value;
			}
		}
		public string Mnemonic
		{
			get
			{
				return this._mnemonic;
			}
			set
			{
				this._mnemonic = value;
			}
		}
		public string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		public string Uri
		{
			get
			{
				return this._uri;
			}
			set
			{
				this._uri = value;
			}
		}
		public IDictionary<string,Energistics.Etp.v12.Datatypes.DataValue> CustomData
		{
			get
			{
				return this._customData;
			}
			set
			{
				this._customData = value;
			}
		}
		public int Scale
		{
			get
			{
				return this._scale;
			}
			set
			{
				this._scale = value;
			}
		}
		public string TimeDatum
		{
			get
			{
				return this._timeDatum;
			}
			set
			{
				this._timeDatum = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._indexKind;
			case 1: return this._uom;
			case 2: return this._depthDatum;
			case 3: return this._direction;
			case 4: return this._mnemonic;
			case 5: return this._description;
			case 6: return this._uri;
			case 7: return this._customData;
			case 8: return this._scale;
			case 9: return this._timeDatum;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._indexKind = (Energistics.Etp.v12.Datatypes.ChannelData.ChannelIndexKinds)fieldValue; break;
			case 1: this._uom = (System.String)fieldValue; break;
			case 2: this._depthDatum = (System.String)fieldValue; break;
			case 3: this._direction = (Energistics.Etp.v12.Datatypes.ChannelData.IndexDirections)fieldValue; break;
			case 4: this._mnemonic = (System.String)fieldValue; break;
			case 5: this._description = (System.String)fieldValue; break;
			case 6: this._uri = (System.String)fieldValue; break;
			case 7: this._customData = (IDictionary<string,Energistics.Etp.v12.Datatypes.DataValue>)fieldValue; break;
			case 8: this._scale = (System.Int32)fieldValue; break;
			case 9: this._timeDatum = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
