// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v11.Protocol.GrowingObject
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class GrowingObjectDeleteRange : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""GrowingObjectDeleteRange"",""namespace"":""Energistics.Protocol.GrowingObject"",""fields"":[{""name"":""uri"",""type"":""string""},{""name"":""startIndex"",""type"":{""type"":""record"",""name"":""GrowingObjectIndex"",""namespace"":""Energistics.Datatypes.Object"",""fields"":[{""name"":""item"",""type"":[""null"",""long"",""double""]}],""fullName"":""Energistics.Datatypes.Object.GrowingObjectIndex"",""depends"":[]}},{""name"":""endIndex"",""type"":""Energistics.Datatypes.Object.GrowingObjectIndex""},{""name"":""uom"",""type"":""string""},{""name"":""depthDatum"",""type"":""string""}],""messageType"":""2"",""protocol"":""6"",""senderRole"":""customer"",""protocolRoles"":""store,customer"",""fullName"":""Energistics.Protocol.GrowingObject.GrowingObjectDeleteRange"",""depends"":[
  ""Energistics.Datatypes.Object.GrowingObjectIndex"",
  ""Energistics.Datatypes.Object.GrowingObjectIndex""
]}");
		private string _uri;
		private Energistics.Etp.v11.Datatypes.Object.GrowingObjectIndex _startIndex;
		private Energistics.Etp.v11.Datatypes.Object.GrowingObjectIndex _endIndex;
		private string _uom;
		private string _depthDatum;
		public virtual Schema Schema
		{
			get
			{
				return GrowingObjectDeleteRange._SCHEMA;
			}
		}
		public string Uri
		{
			get
			{
				return this._uri;
			}
			set
			{
				this._uri = value;
			}
		}
		public Energistics.Etp.v11.Datatypes.Object.GrowingObjectIndex StartIndex
		{
			get
			{
				return this._startIndex;
			}
			set
			{
				this._startIndex = value;
			}
		}
		public Energistics.Etp.v11.Datatypes.Object.GrowingObjectIndex EndIndex
		{
			get
			{
				return this._endIndex;
			}
			set
			{
				this._endIndex = value;
			}
		}
		public string Uom
		{
			get
			{
				return this._uom;
			}
			set
			{
				this._uom = value;
			}
		}
		public string DepthDatum
		{
			get
			{
				return this._depthDatum;
			}
			set
			{
				this._depthDatum = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._uri;
			case 1: return this._startIndex;
			case 2: return this._endIndex;
			case 3: return this._uom;
			case 4: return this._depthDatum;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._uri = (System.String)fieldValue; break;
			case 1: this._startIndex = (Energistics.Etp.v11.Datatypes.Object.GrowingObjectIndex)fieldValue; break;
			case 2: this._endIndex = (Energistics.Etp.v11.Datatypes.Object.GrowingObjectIndex)fieldValue; break;
			case 3: this._uom = (System.String)fieldValue; break;
			case 4: this._depthDatum = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
