// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.ChannelStreaming
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class TruncateChannels : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""TruncateChannels"",""namespace"":""Energistics.Etp.v12.Protocol.ChannelStreaming"",""fields"":[{""name"":""channels"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""TruncateInfo"",""namespace"":""Energistics.Etp.v12.Datatypes.ChannelData"",""fields"":[{""name"":""channelId"",""type"":""long""},{""name"":""newEndIndex"",""type"":{""type"":""record"",""name"":""IndexValue"",""namespace"":""Energistics.Etp.v12.Datatypes"",""fields"":[{""name"":""item"",""type"":[""null"",""long"",""double""]}],""fullName"":""Energistics.Etp.v12.Datatypes.IndexValue"",""depends"":[]}}],""fullName"":""Energistics.Etp.v12.Datatypes.ChannelData.TruncateInfo"",""depends"":[
  ""Energistics.Etp.v12.Datatypes.IndexValue""
]}}}],""protocol"":""1"",""messageType"":""5"",""senderRole"":""producer"",""protocolRoles"":""producer,consumer"",""multipartFlag"":false,""fullName"":""Energistics.Etp.v12.Protocol.ChannelStreaming.TruncateChannels"",""depends"":[
  ""Energistics.Etp.v12.Datatypes.ChannelData.TruncateInfo""
]}");
		private IList<Energistics.Etp.v12.Datatypes.ChannelData.TruncateInfo> _channels;
		public virtual Schema Schema
		{
			get
			{
				return TruncateChannels._SCHEMA;
			}
		}
		public IList<Energistics.Etp.v12.Datatypes.ChannelData.TruncateInfo> Channels
		{
			get
			{
				return this._channels;
			}
			set
			{
				this._channels = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._channels;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._channels = (IList<Energistics.Etp.v12.Datatypes.ChannelData.TruncateInfo>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
