// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v11.Datatypes.ChannelData
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class ChannelStreamingInfo : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""ChannelStreamingInfo"",""namespace"":""Energistics.Datatypes.ChannelData"",""fields"":[{""name"":""channelId"",""type"":""long""},{""name"":""startIndex"",""type"":{""type"":""record"",""name"":""StreamingStartIndex"",""namespace"":""Energistics.Datatypes.ChannelData"",""fields"":[{""name"":""item"",""type"":[""null"",""int"",""long""]}],""fullName"":""Energistics.Datatypes.ChannelData.StreamingStartIndex"",""depends"":[]}},{""name"":""receiveChangeNotification"",""type"":""boolean""}],""fullName"":""Energistics.Datatypes.ChannelData.ChannelStreamingInfo"",""depends"":[
  ""Energistics.Datatypes.ChannelData.StreamingStartIndex""
]}");
		private long _channelId;
		private Energistics.Etp.v11.Datatypes.ChannelData.StreamingStartIndex _startIndex;
		private bool _receiveChangeNotification;
		public virtual Schema Schema
		{
			get
			{
				return ChannelStreamingInfo._SCHEMA;
			}
		}
		public long ChannelId
		{
			get
			{
				return this._channelId;
			}
			set
			{
				this._channelId = value;
			}
		}
		public Energistics.Etp.v11.Datatypes.ChannelData.StreamingStartIndex StartIndex
		{
			get
			{
				return this._startIndex;
			}
			set
			{
				this._startIndex = value;
			}
		}
		public bool ReceiveChangeNotification
		{
			get
			{
				return this._receiveChangeNotification;
			}
			set
			{
				this._receiveChangeNotification = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._channelId;
			case 1: return this._startIndex;
			case 2: return this._receiveChangeNotification;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._channelId = (System.Int64)fieldValue; break;
			case 1: this._startIndex = (Energistics.Etp.v11.Datatypes.ChannelData.StreamingStartIndex)fieldValue; break;
			case 2: this._receiveChangeNotification = (System.Boolean)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
