// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v11.Datatypes.ChannelData
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class ChannelMetadataRecord : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ChannelMetadataRecord\",\"namespace\":\"Energistics.Datatype" +
				"s.ChannelData\",\"fields\":[{\"name\":\"channelUri\",\"type\":\"string\"},{\"name\":\"channelI" +
				"d\",\"type\":\"long\"},{\"name\":\"indexes\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"reco" +
				"rd\",\"name\":\"IndexMetadataRecord\",\"namespace\":\"Energistics.Datatypes.ChannelData\"" +
				",\"fields\":[{\"name\":\"indexType\",\"type\":{\"type\":\"enum\",\"name\":\"ChannelIndexTypes\"," +
				"\"namespace\":\"Energistics.Datatypes.ChannelData\",\"symbols\":[\"Time\",\"Depth\"],\"full" +
				"Name\":\"Energistics.Datatypes.ChannelData.ChannelIndexTypes\",\"depends\":[]}},{\"nam" +
				"e\":\"uom\",\"type\":\"string\"},{\"name\":\"depthDatum\",\"type\":[\"null\",\"string\"]},{\"name\"" +
				":\"direction\",\"type\":{\"type\":\"enum\",\"name\":\"IndexDirections\",\"namespace\":\"Energis" +
				"tics.Datatypes.ChannelData\",\"symbols\":[\"Increasing\",\"Decreasing\"],\"fullName\":\"En" +
				"ergistics.Datatypes.ChannelData.IndexDirections\",\"depends\":[]}},{\"name\":\"mnemoni" +
				"c\",\"type\":[\"null\",\"string\"]},{\"name\":\"description\",\"type\":[\"null\",\"string\"]},{\"n" +
				"ame\":\"uri\",\"type\":[\"null\",\"string\"]},{\"name\":\"customData\",\"type\":{\"type\":\"map\",\"" +
				"values\":{\"type\":\"record\",\"name\":\"DataValue\",\"namespace\":\"Energistics.Datatypes\"," +
				"\"fields\":[{\"name\":\"item\",\"type\":[\"null\",\"double\",\"float\",\"int\",\"long\",\"string\",{" +
				"\"type\":\"record\",\"name\":\"ArrayOfDouble\",\"namespace\":\"Energistics.Datatypes\",\"fiel" +
				"ds\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"double\"}}],\"fullName\":\"Ene" +
				"rgistics.Datatypes.ArrayOfDouble\",\"depends\":[]},\"boolean\",\"bytes\"]}],\"fullName\":" +
				"\"Energistics.Datatypes.DataValue\",\"depends\":[\r\n  \"Energistics.Datatypes.ArrayOfD" +
				"ouble\"\r\n]}}},{\"name\":\"scale\",\"type\":\"int\"},{\"name\":\"timeDatum\",\"type\":[\"null\",\"s" +
				"tring\"]}],\"fullName\":\"Energistics.Datatypes.ChannelData.IndexMetadataRecord\",\"de" +
				"pends\":[\r\n  \"Energistics.Datatypes.ChannelData.ChannelIndexTypes\",\r\n  \"Energisti" +
				"cs.Datatypes.ChannelData.IndexDirections\",\r\n  \"Energistics.Datatypes.DataValue\"\r" +
				"\n]}}},{\"name\":\"channelName\",\"type\":\"string\"},{\"name\":\"dataType\",\"type\":\"string\"}" +
				",{\"name\":\"uom\",\"type\":\"string\"},{\"name\":\"startIndex\",\"type\":[\"null\",\"long\"]},{\"n" +
				"ame\":\"endIndex\",\"type\":[\"null\",\"long\"]},{\"name\":\"description\",\"type\":\"string\"},{" +
				"\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"ChannelStatuses\",\"namespace\":\"Ener" +
				"gistics.Datatypes.ChannelData\",\"symbols\":[\"Active\",\"Inactive\",\"Closed\"],\"fullNam" +
				"e\":\"Energistics.Datatypes.ChannelData.ChannelStatuses\",\"depends\":[]}},{\"name\":\"c" +
				"ontentType\",\"type\":[\"null\",\"string\"]},{\"name\":\"source\",\"type\":\"string\"},{\"name\":" +
				"\"measureClass\",\"type\":\"string\"},{\"name\":\"uuid\",\"type\":[\"null\",\"string\"]},{\"name\"" +
				":\"customData\",\"type\":{\"type\":\"map\",\"values\":\"Energistics.Datatypes.DataValue\"}}," +
				"{\"name\":\"domainObject\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"DataObject\",\"name" +
				"space\":\"Energistics.Datatypes.Object\",\"fields\":[{\"name\":\"resource\",\"type\":{\"type" +
				"\":\"record\",\"name\":\"Resource\",\"namespace\":\"Energistics.Datatypes.Object\",\"fields\"" +
				":[{\"name\":\"uri\",\"type\":\"string\"},{\"name\":\"contentType\",\"type\":\"string\"},{\"name\":" +
				"\"name\",\"type\":\"string\"},{\"name\":\"channelSubscribable\",\"type\":\"boolean\"},{\"name\":" +
				"\"customData\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"resourceType\",\"ty" +
				"pe\":\"string\"},{\"name\":\"hasChildren\",\"type\":\"int\"},{\"name\":\"uuid\",\"type\":[\"null\"," +
				"\"string\"]},{\"name\":\"lastChanged\",\"type\":\"long\"},{\"name\":\"objectNotifiable\",\"type" +
				"\":\"boolean\"}],\"fullName\":\"Energistics.Datatypes.Object.Resource\",\"depends\":[]}}," +
				"{\"name\":\"contentEncoding\",\"type\":\"string\"},{\"name\":\"data\",\"type\":\"bytes\"}],\"full" +
				"Name\":\"Energistics.Datatypes.Object.DataObject\",\"depends\":[\r\n  \"Energistics.Data" +
				"types.Object.Resource\"\r\n]}]}],\"fullName\":\"Energistics.Datatypes.ChannelData.Chan" +
				"nelMetadataRecord\",\"depends\":[\r\n  \"Energistics.Datatypes.ChannelData.IndexMetada" +
				"taRecord\",\r\n  \"Energistics.Datatypes.ChannelData.ChannelStatuses\",\r\n  \"Energisti" +
				"cs.Datatypes.DataValue\",\r\n  \"Energistics.Datatypes.Object.DataObject\"\r\n]}");
		private string _channelUri;
		private long _channelId;
		private IList<Energistics.Etp.v11.Datatypes.ChannelData.IndexMetadataRecord> _indexes;
		private string _channelName;
		private string _dataType;
		private string _uom;
		private System.Nullable<long> _startIndex;
		private System.Nullable<long> _endIndex;
		private string _description;
		private Energistics.Etp.v11.Datatypes.ChannelData.ChannelStatuses _status;
		private string _contentType;
		private string _source;
		private string _measureClass;
		private string _uuid;
		private IDictionary<string,Energistics.Etp.v11.Datatypes.DataValue> _customData;
		private Energistics.Etp.v11.Datatypes.Object.DataObject _domainObject;
		public virtual Schema Schema
		{
			get
			{
				return ChannelMetadataRecord._SCHEMA;
			}
		}
		public string ChannelUri
		{
			get
			{
				return this._channelUri;
			}
			set
			{
				this._channelUri = value;
			}
		}
		public long ChannelId
		{
			get
			{
				return this._channelId;
			}
			set
			{
				this._channelId = value;
			}
		}
		public IList<Energistics.Etp.v11.Datatypes.ChannelData.IndexMetadataRecord> Indexes
		{
			get
			{
				return this._indexes;
			}
			set
			{
				this._indexes = value;
			}
		}
		public string ChannelName
		{
			get
			{
				return this._channelName;
			}
			set
			{
				this._channelName = value;
			}
		}
		public string DataType
		{
			get
			{
				return this._dataType;
			}
			set
			{
				this._dataType = value;
			}
		}
		public string Uom
		{
			get
			{
				return this._uom;
			}
			set
			{
				this._uom = value;
			}
		}
		public System.Nullable<long> StartIndex
		{
			get
			{
				return this._startIndex;
			}
			set
			{
				this._startIndex = value;
			}
		}
		public System.Nullable<long> EndIndex
		{
			get
			{
				return this._endIndex;
			}
			set
			{
				this._endIndex = value;
			}
		}
		public string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		public Energistics.Etp.v11.Datatypes.ChannelData.ChannelStatuses Status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		public string ContentType
		{
			get
			{
				return this._contentType;
			}
			set
			{
				this._contentType = value;
			}
		}
		public string Source
		{
			get
			{
				return this._source;
			}
			set
			{
				this._source = value;
			}
		}
		public string MeasureClass
		{
			get
			{
				return this._measureClass;
			}
			set
			{
				this._measureClass = value;
			}
		}
		public string Uuid
		{
			get
			{
				return this._uuid;
			}
			set
			{
				this._uuid = value;
			}
		}
		public IDictionary<string,Energistics.Etp.v11.Datatypes.DataValue> CustomData
		{
			get
			{
				return this._customData;
			}
			set
			{
				this._customData = value;
			}
		}
		public Energistics.Etp.v11.Datatypes.Object.DataObject DomainObject
		{
			get
			{
				return this._domainObject;
			}
			set
			{
				this._domainObject = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._channelUri;
			case 1: return this._channelId;
			case 2: return this._indexes;
			case 3: return this._channelName;
			case 4: return this._dataType;
			case 5: return this._uom;
			case 6: return this._startIndex;
			case 7: return this._endIndex;
			case 8: return this._description;
			case 9: return this._status;
			case 10: return this._contentType;
			case 11: return this._source;
			case 12: return this._measureClass;
			case 13: return this._uuid;
			case 14: return this._customData;
			case 15: return this._domainObject;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._channelUri = (System.String)fieldValue; break;
			case 1: this._channelId = (System.Int64)fieldValue; break;
			case 2: this._indexes = (IList<Energistics.Etp.v11.Datatypes.ChannelData.IndexMetadataRecord>)fieldValue; break;
			case 3: this._channelName = (System.String)fieldValue; break;
			case 4: this._dataType = (System.String)fieldValue; break;
			case 5: this._uom = (System.String)fieldValue; break;
			case 6: this._startIndex = (System.Nullable<long>)fieldValue; break;
			case 7: this._endIndex = (System.Nullable<long>)fieldValue; break;
			case 8: this._description = (System.String)fieldValue; break;
			case 9: this._status = (Energistics.Etp.v11.Datatypes.ChannelData.ChannelStatuses)fieldValue; break;
			case 10: this._contentType = (System.String)fieldValue; break;
			case 11: this._source = (System.String)fieldValue; break;
			case 12: this._measureClass = (System.String)fieldValue; break;
			case 13: this._uuid = (System.String)fieldValue; break;
			case 14: this._customData = (IDictionary<string,Energistics.Etp.v11.Datatypes.DataValue>)fieldValue; break;
			case 15: this._domainObject = (Energistics.Etp.v11.Datatypes.Object.DataObject)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
