// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.ChannelDataFrame
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class GetFrameResponseHeader : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""GetFrameResponseHeader"",""namespace"":""Energistics.Etp.v12.Protocol.ChannelDataFrame"",""fields"":[{""name"":""channelUris"",""type"":{""type"":""array"",""items"":""string""}}],""protocol"":""2"",""messageType"":""4"",""senderRole"":""store"",""protocolRoles"":""store,customer"",""multipartFlag"":true,""fullName"":""Energistics.Etp.v12.Protocol.ChannelDataFrame.GetFrameResponseHeader"",""depends"":[]}");
		private IList<System.String> _channelUris;
		public virtual Schema Schema
		{
			get
			{
				return GetFrameResponseHeader._SCHEMA;
			}
		}
		public IList<System.String> ChannelUris
		{
			get
			{
				return this._channelUris;
			}
			set
			{
				this._channelUris = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._channelUris;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._channelUris = (IList<System.String>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
