// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes.Object
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class ObjectChange : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ObjectChange\",\"namespace\":\"Energistics.Etp.v12.Datatypes" +
				".Object\",\"fields\":[{\"name\":\"changeKind\",\"type\":{\"type\":\"enum\",\"name\":\"ObjectChan" +
				"geKind\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Object\",\"symbols\":[\"insert\",\"" +
				"update\",\"authorized\"],\"fullName\":\"Energistics.Etp.v12.Datatypes.Object.ObjectCha" +
				"ngeKind\",\"depends\":[]}},{\"name\":\"changeTime\",\"type\":\"long\"},{\"name\":\"dataObject\"" +
				",\"type\":{\"type\":\"record\",\"name\":\"DataObject\",\"namespace\":\"Energistics.Etp.v12.Da" +
				"tatypes.Object\",\"fields\":[{\"name\":\"resource\",\"type\":{\"type\":\"record\",\"name\":\"Res" +
				"ource\",\"namespace\":\"Energistics.Etp.v12.Datatypes.Object\",\"fields\":[{\"name\":\"uri" +
				"\",\"type\":\"string\"},{\"name\":\"alternateUris\",\"default\":[],\"type\":{\"type\":\"array\",\"" +
				"items\":\"string\"}},{\"name\":\"dataObjectType\",\"type\":\"string\"},{\"name\":\"name\",\"type" +
				"\":\"string\"},{\"name\":\"sourceCount\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":" +
				"\"targetCount\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"lastChanged\",\"type\"" +
				":\"long\"},{\"name\":\"customData\",\"default\":{},\"type\":{\"type\":\"map\",\"values\":\"string" +
				"\"}}],\"fullName\":\"Energistics.Etp.v12.Datatypes.Object.Resource\",\"depends\":[]}},{" +
				"\"name\":\"format\",\"default\":\"xml\",\"type\":\"string\"},{\"name\":\"blobId\",\"type\":[\"null\"" +
				",{\"type\":\"fixed\",\"name\":\"Uuid\",\"namespace\":\"Energistics.Etp.v12.Datatypes\",\"size" +
				"\":16,\"fullName\":\"Energistics.Etp.v12.Datatypes.Uuid\",\"depends\":[]}]},{\"name\":\"da" +
				"ta\",\"default\":\"\",\"type\":\"bytes\"}],\"fullName\":\"Energistics.Etp.v12.Datatypes.Obje" +
				"ct.DataObject\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.Object.Resource\",\r\n" +
				"  \"Energistics.Etp.v12.Datatypes.Uuid\"\r\n]}}],\"fullName\":\"Energistics.Etp.v12.Dat" +
				"atypes.Object.ObjectChange\",\"depends\":[\r\n  \"Energistics.Etp.v12.Datatypes.Object" +
				".ObjectChangeKind\",\r\n  \"Energistics.Etp.v12.Datatypes.Object.DataObject\"\r\n]}");
		private Energistics.Etp.v12.Datatypes.Object.ObjectChangeKind _changeKind;
		private long _changeTime;
		private Energistics.Etp.v12.Datatypes.Object.DataObject _dataObject;
		public virtual Schema Schema
		{
			get
			{
				return ObjectChange._SCHEMA;
			}
		}
		public Energistics.Etp.v12.Datatypes.Object.ObjectChangeKind ChangeKind
		{
			get
			{
				return this._changeKind;
			}
			set
			{
				this._changeKind = value;
			}
		}
		public long ChangeTime
		{
			get
			{
				return this._changeTime;
			}
			set
			{
				this._changeTime = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.Object.DataObject DataObject
		{
			get
			{
				return this._dataObject;
			}
			set
			{
				this._dataObject = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._changeKind;
			case 1: return this._changeTime;
			case 2: return this._dataObject;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._changeKind = (Energistics.Etp.v12.Datatypes.Object.ObjectChangeKind)fieldValue; break;
			case 1: this._changeTime = (System.Int64)fieldValue; break;
			case 2: this._dataObject = (Energistics.Etp.v12.Datatypes.Object.DataObject)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
